### ISSUE TITLE
Squid service wrongly detect as down

### ISSUE THREAD

**Issue by GabrieleV** [rbicelli/pfsense-zabbix-template#1]
On my pfsense box squid service is detected as down, but it is running. Only reverse proxy service is stopped.

**Comment by rbicelli** [comment]
Hi! Currently I don't have any pfsense boxes monitored with squid installed. Will fire a test vm ASAP.

**Comment by rbicelli** [comment]
Please checkout the development branch, I added a function for testing purposes in help to develop the template. Call it in a ssh shell without arguments:

php /path/to/script/pfsense_zbx.php

then post the result of "Services" section.

Thanks

**Comment by rbicelli** [comment]
Close since no info provided
