### ISSUE TITLE
Can't run discovery or get any data

### ISSUE THREAD

**Issue by tientmse62290** [rbicelli/pfsense-zabbix-template#10]
Hi, after following the instruction but I can't get any data into my zabbix server. The most data I want is openvpn. Any solution to find out what happen?
![image](https://user-images.githubusercontent.com/28757980/77321187-65b84400-6d44-11ea-9e7d-1cda1ad80433.png)
Thanks & Regards

**Comment by rbicelli** [comment]
Hi, please checkout latest commit.

**Comment by tientmse62290** [comment]
Hi @rbicelli 
I updated to latest version and it not changes
![image](https://user-images.githubusercontent.com/28757980/77816631-b1793d80-70f6-11ea-946f-a3d96a27830d.png)

**Comment by rbicelli** [comment]
If you are trying to force the discovery selecting the rule and then clicking on "check now" this is normal behaviour, I think. Same happens to me. But if you wait some time you could see the items created.

**Comment by tientmse62290** [comment]
normal data can't show too and I dont know why
![image](https://user-images.githubusercontent.com/28757980/77820818-c2867680-7117-11ea-818e-ef3bfa7b715c.png)

**Comment by rbicelli** [comment]
Any clues in zabbix server log and/or pfsense zabbix agent log?
Are you sure that hostname configured on Zabbix agent on pfSense is the same on Zabbix server?

**Comment by tientmse62290** [comment]
Hi I updated to zabbix agent 4.4 and set fw rule and it work. Thanks

**Comment by tientmse62290** [comment]
![image](https://user-images.githubusercontent.com/28757980/77843757-806a3d00-71ca-11ea-8d6f-e91b6d3cb4d4.png)
I have graph and got the message: "No permissions to referred object or it does not exist!"
But the item "OpenVPN Server Remote Users Clients Connected" till show with real data
