### ISSUE TITLE
Servie Discovery Not supported

### ISSUE THREAD

**Issue by WiwisLab** [rbicelli/pfsense-zabbix-template#100]
Hello !
First I want to thank you for this nice job ! I'm new on zabbix and these script and template are really easy to use !
But as I'm new, I probably mistake somewhere in my config...

I'm monitoring a pfsense 2.5.2 with zabbix agent 5.4, and my zabbix server is 5.4 too.
Everything is working well except the Service Discovery which appear as Not Supported on zabbix server with the problem :
Global regular expression "pfSense service names for discovery" does not exist.
 
https://ibb.co/WszkJLR

I don't know what I forgot, or where I'm supposed to solve that...
Maybe is it because I'm using version 5.4 ?

Thanks

**Comment by rbicelli** [comment]
Hello, looks like you are missing a global regexp "pfSense service names for discovery":
![immagine](https://user-images.githubusercontent.com/3899694/149990466-d2b23815-fa49-42b1-8ba5-6c01d40c31d6.png)

**Comment by WiwisLab** [comment]
Hello and thank you very much ! it was exactly my problem

And thanks for your work, it's working perfectly !
