### ISSUE TITLE
Template notworking : Pfsense 2.5.2-RELEASE (amd64), Zabbix agent 5.4

### ISSUE THREAD

**Issue by vinhthai1989** [rbicelli/pfsense-zabbix-template#101]
Hi admin, I am using Pfsense 2.5.2-RELEASE (amd64), Zabbix server 5.4 and Zabbix agent 5.4  
The host Zabbix's Availability is not green. But when I use Template FreeBSD it's working.  Can anyone help me, please!

![image](https://user-images.githubusercontent.com/87307317/150264323-4d13ee76-ba93-4075-81b6-9dd6b954c81c.png)

**Comment by GuillaumeHullin** [comment]
Hi @vinhthai1989,
To look if the availability in Zabbix is green or not is not the way to check if a template is working. For understanding why I'm saying this you can read this https://www.zabbix.com/documentation/5.0/en/manual/web_interface/frontend_sections/configuration/hosts#reading-host-availability 

>Zabbix server sets the host availability icon to gray (unknown status) for the corresponding agent interface (Zabbix, SNMP, IPMI, JMX) if:
> - there are only active Zabbix agent items;

This template include only active Zabbix Agent... hence why availability is greyed.

The first question to ask, to check if the template is working, "do you get data?"

**Comment by vinhthai1989** [comment]
> Hi @vinhthai1989, To look if the availability in Zabbix is green or not is not the way to check if a template is working. For understanding why I'm saying this you can read this https://www.zabbix.com/documentation/5.0/en/manual/web_interface/frontend_sections/configuration/hosts#reading-host-availability
> 
> > Zabbix server sets the host availability icon to gray (unknown status) for the corresponding agent interface (Zabbix, SNMP, IPMI, JMX) if:
> > 
> > * there are only active Zabbix agent items;
> 
> This template include only active Zabbix Agent... hence why availability is greyed.
> 
> The first question to ask, to check if the template is working, "do you get data?"

Thank you so much, I understand now. But After checking I found there are data except for two:
OpenVPN Server Discovery and Monitoring (Server Status/Tunnel Status)
OpenVPN Clients Discovery and Monitoring (Client Status/Tunnel Status)

I checked the "Graphs" it is not showing anything about the two above.
![image](https://user-images.githubusercontent.com/87307317/150737335-1a1881a8-31dd-4d36-831f-f04243e3170b.png)
![image](https://user-images.githubusercontent.com/87307317/150737481-56ba6c0e-8b60-41ab-ada7-d2ccadde47a0.png)

How to fix it?

**Comment by GuillaumeHullin** [comment]
@vinhthai1989 You're welcome. If that solve the issue, please close this issue ;)

**Comment by vinhthai1989** [comment]
Hi @GuillaumeHullin, I have a question: this template has a temperature graphic?
Thank

**Comment by GuillaumeHullin** [comment]
@vinhthai1989 Not that I know of. Anyway for me it's slightly useless cause I run pfSense most of the time inside a VM and I usually monitor with Zabbix the hypervisor embedded server management (like iLO). 

But I think this template can monitor SMART data. Sometimes the drive temperature is in the smart data.
