### ISSUE TITLE
Not supported by Zabbix Agent

### ISSUE THREAD

**Issue by misteradamx** [rbicelli/pfsense-zabbix-template#103]
Getting the following error with the Discovery rules and with some of the items, specifically any that have the pfsense.value key set.
`Not supported by Zabbix Agent`

I'm running a pfsense+ appliance from NetGate .
```
21.05.2-RELEASE (amd64)
built on Fri Oct 22 15:24:02 UTC 2021
FreeBSD 12.2-STABLE
```
I am running Zabbix 5.0.19 and I've tried both agent packages (5.0.11 and 5.4.2).

**Comment by rbicelli** [comment]
Did you followed instructions? Did you configured the agent for active checks?

**Comment by misteradamx** [comment]
> 

![dUXhOqu 1](https://user-images.githubusercontent.com/22596467/151439443-25e978da-8576-4f34-9e7c-2faa99989a35.png)
These are my settings in the Package Management. The server never fully sees the agent using the active port. Is this not set correctly? (In this screenshot, I also removed the ListenPort line to test) 

I cannot find any documentation that accurate conveys how to set up the agent for this method or how to troubleshoot.

**Comment by rbicelli** [comment]
In server active you can omit the port.
Hostname must match the hostname in zabbix.

**Comment by misteradamx** [comment]
> In server active you can omit the port. Hostname must match the hostname in zabbix.

Hostname is the same as in Zabbix. If I use the normal agent setup with the normal port, it works. 
I have the agent line in Zabbix set to the IP and the port set to 10051. Is this correct?

**Comment by randysrs** [comment]
any update here ?  version 5.4.2 upload newest XML's same issue . 
![image](https://user-images.githubusercontent.com/58384233/153945126-a8558ad5-d2d3-45a8-b740-5fde5b68bf88.png)

**Comment by GuillaumeHullin** [comment]
@randysrs, in pfSense > Services > Cron, do you see the following line?   `/usr/local/bin/php /root/scripts/pfsense_zbx.php`

What do you get if you run
  
```
# This should show the speediest result
cat /tmp/speedtest-em0

#This should parse the result and only give you the download speed
/usr/local/bin/php /root/scripts/pfsense_zbx.php if_speedtest_value em0 download

# Note that I'm assuming that your WAN is the interface em0 (check Interface > Assignments)
```

**Comment by randysrs** [comment]
***@***.***/root: dig github.com

; <<>> DiG 9.16.16 <<>> github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63818
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;github.com.                    IN      A

;; ANSWER SECTION:
github.com.             60      IN      A       192.30.255.112

;; Query time: 36 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Feb 16 00:54:09 PST 2022
;; MSG SIZE  rcvd: 55

**Comment by GuillaumeHullin** [comment]
Ok. Run the following to make sure you have the latest speedtest package.

```
pkg update && pkg install -y  -g 'py*-speedtest-cli'
```

One other point, can you comment back via GitHub app or website but not by answering mail... somehow the output is hard to sort out quickly.

**Comment by randysrs** [comment]
pkg update && pkg install -y  -g 'py*-speedtest-cli'
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed

**Comment by GuillaumeHullin** [comment]
Ok so if the package is installed correctly... it seems like a DNS issue with your pfSense.

In pfSense > System > General Setup

What is your DNS? Is it local or is it remote?
What is your DNS Resolution Behavior

IMO, I would setup DNS as 1.1.1.1 (Cloudflare) and 8.8.8.8 (Google) and setup DNS resolution as "use Local then fall back to remote (Google/Cloudflare)"

Maybe you can try to set your remote DNS and set the DNS resolution as "use remote and ignore local". Be careful you might disturb your network if you are on a live environment. I would also advice a reboot in order to make sure your DNS are set in the system properly.

Then try again `/usr/local/bin/speedtest --list`

**Comment by randysrs** [comment]
current DNS 
8.8.8.8 , 4.2.2.2 and 173.248.59.127

when i run /usr/local/bin/speedtest --list

Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: HTTP Error 404: Not Found

**Comment by misteradamx** [comment]
I continue to have issues utilizing the templates. If I do an import and immediately try to run the Discovery rules, I got the following still: `Cannot send request: wrong discovery rule type.`

**Comment by GuillaumeHullin** [comment]
@misteradamx sorry I don't have time to re-read the thread it but concerning `Cannot send request: wrong discovery rule type.` this is completely normal and expected. The discovery items are Zabbix Active Agent... so you can't use `Execute Now` from your Zabbix Server.
