### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by MrChunks** [rbicelli/pfsense-zabbix-template#104]
This was easy to figure out (though it took me longer than it should have....)

The path for PHP has a typo - it's looking in **/url/**... not **/usr/**...

To remove the speedtest cron job, the documentation says to run:

`/url/local/bin/php /root/scripts/pfsense_zbx.php cron_cleanup`

but I think it should be
`/usr/local/bin/php /root/scripts/pfsense_zbx.php cron_cleanup`

**Comment by GuillaumeHullin** [comment]
On it :) Thanks for the data #105
