### ISSUE TITLE
Crash on pfsense+ 22.01

### ISSUE THREAD

**Issue by danjeman** [rbicelli/pfsense-zabbix-template#109]
Upgraded a number of SG2100's and XG7100s from +21.05 to 22.01 and on the most recent (so using current script as haven't got round to upgrading script on all) install started to see a crash report...

[17-Feb-2022 00:21:15 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function get_ipsecifnum() in /root/scripts/pfsense_zbx.php:668
Stack trace:
#0 /root/scripts/pfsense_zbx.php(580): pfz_ipsec_status('1')
#1 /root/scripts/pfsense_zbx.php(1274): pfz_ipsec_ph1('1', 'status')
#2 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 668

Everything else looks to be working ok and on units with older code no crash and all appears to be working currently although checking through that now....

Have a few VMs running 2.5.2 so will be upgrading those to 2.6 and also going to try migrating to plus on a couple of those as well so will report back after that as well but suspect it is a plus code change...

**Comment by DerRealKeyser** [comment]
I can confirm I'm seeing the exact same issue after reinstalling pfSense 22.01 from scratch and reimporting the latest script with the Zabbix 5.0 agent

**Comment by rbicelli** [comment]
I have not already updated any of my machines to 2.6 or tried pfSense+.
As soon as I can I will fire up a + test environment and add a pfSense+ version of the template.

**Comment by DerRealKeyser** [comment]
That would be cool, because I have to disable Zabbix monitoring until it is fixed. The script crashes every minute and causes a lot of notifications and fault reports.

**Comment by rbicelli** [comment]
For now you could try disabling ipsec features only, php crashes are related to ipsec calls which I suppose were rewritten in pfsense+ codebase.

**Comment by DerRealKeyser** [comment]
It was the "pfsense active ipsec" template that triggered sections in the pfsense_zbx.php script that causes the failures.
I have unlinked the template for now and stopped monitoring my IPsec tunnels until a fix is hopefully found :-)
Thanks !

**Comment by rbicelli** [comment]
Hopefully is solved with PR #118. Please check.
