### ISSUE TITLE
OpenVPN Discovery Issue

### ISSUE THREAD

**Issue by raphazippin** [rbicelli/pfsense-zabbix-template#11]
I can't get OpenVPN Server status and port

**Comment by raphazippin** [comment]
Preprocessing failed for: 1197
1. Result: 1197p2p_tls=1:p2p_shared_key:2,server_tls:3,server_user:4,server_tls_user:5
2. Failed: cannot perform regular expression "(p2p_tls,p2p_shared_key,server_tls,server_user,server_tls_user)" match for value of type "string": pattern does not match

**Comment by raphazippin** [comment]
Status stays down all the time. Regarding the door, I just removed the preprocessing

**Comment by rbicelli** [comment]
It seems last PR broke something. Will do some troubleshooting.

**Comment by rbicelli** [comment]
Please checkout latest commit. Restructured the template from broken PRs.
