### ISSUE TITLE
Global regular expression "pfSense service names for discovery" does not exist.

### ISSUE THREAD

**Issue by DerRealKeyser** [rbicelli/pfsense-zabbix-template#110]
Apart from the script crash on ipsec discovery (as mentioned in another issue report), I also get a "Global regular expression "pfSense service names for discovery" does not exist." for the services discovery rule and it is marked "Not supported".

Again, this is on pfSense+ 22.01 with the latest templates and script.

**Comment by rbicelli** [comment]
You need to create it manually in Zabbix under Administration->General->Regular Expressions

**Comment by DerRealKeyser** [comment]
Thanks, that fixed the issue. I'm fairlt new to zabbix, so I did not know this was something I had to create myself.
It would be a good idea to include that in your basic setup guide :-)
