### ISSUE TITLE
Service Quagga OSPFd Error

### ISSUE THREAD

**Issue by raphazippin** [rbicelli/pfsense-zabbix-template#12]
Value "" of type "string" is not suitable for value type "Numeric (unsigned)"

![image](https://user-images.githubusercontent.com/12687695/77430778-760b0600-6dba-11ea-8f7b-dc85ccce9c41.png)

**Comment by rbicelli** [comment]
It's because service name contains spaces.

Addressed in latest commit (replaced spaces in service name with "__").

**Comment by rbicelli** [comment]
Solved in latest commit
