### ISSUE TITLE
Host group "Templates/Network devices" already exists.

### ISSUE THREAD

**Issue by sistemasanquan** [rbicelli/pfsense-zabbix-template#121]
hello,

I can't update the template to the new version, I get the following error. Maybe I'm updating it wrong. Thanks in advance

![2022-06-24 10_26_43-Window](https://user-images.githubusercontent.com/99823757/175556423-589c09c4-457f-471a-96e2-a494227033be.png)

**Comment by Adrianoebm** [comment]
Edit all .xml you have a case sensitive problem like me.
Inside the .xml rename the lines with Templates/Network Devices to Templates/Network devices.
