### ISSUE TITLE
undefined function get_ipsecifnum()

### ISSUE THREAD

**Issue by leandro-palombo** [rbicelli/pfsense-zabbix-template#122]
PHP ERROR: Type: 1, File: /root/scripts/pfsense_zbx.php, Line: 668, Message: Uncaught Error: Call to undefined function get_ipsecifnum() in /root/scripts/pfsense_zbx.php:668Stack trace:#0 /root/scripts/pfsense_zbx.php(580): pfz_ipsec_status('1')#1 /root/scripts/pfsense_zbx.php(1274): pfz_ipsec_ph1('1', 'status')#2 {main}thrown @ 2022-07-13 17:07:26

Hello!
I could not find the function get_ipsecifnum() in the code?
Any thoughts on that guys??

Thanks for the support!

**Comment by Flawioo** [comment]
It was solved at https://github.com/rbicelli/pfsense-zabbix-template/pull/118

**Comment by rbicelli** [comment]
Fixed in PR #118
