### ISSUE TITLE
Uncaught exception on pfsense 2.6

### ISSUE THREAD

**Issue by shnacharya** [rbicelli/pfsense-zabbix-template#123]
PHP ERROR: Type: 1, File: /root/scripts/pfsense_zbx.php, Line: 668, Message: Uncaught Error: Call to undefined function get_ipsecifnum() in /root/scripts/pfsense_zbx.php:668
Stack trace:
#0 /root/scripts/pfsense_zbx.php(580): pfz_ipsec_status('1')
#1 /root/scripts/pfsense_zbx.php(1274): pfz_ipsec_ph1('1', 'status')
#2 {main}
thrown @ 2022-08-11 21:02:12

**Comment by rbicelli** [comment]
Fixed in PR #118
