### ISSUE TITLE
pfSense 2.6 zabbix 6

### ISSUE THREAD

**Issue by 18vamberto** [rbicelli/pfsense-zabbix-template#124]
Good Morning

This error is occurring in pfsense 2.6 version with zabbix 6, any position?

Yours sincerely

PHP ERROR: Type: 1, File: /root/scripts/pfsense_zbx.php, Line: 668, Message: Uncaught Error: Call to undefined function get_ipsecifnum() in /root/scripts/pfsense_zbx.php:668
Stack trace:
#0 /root/scripts/pfsense_zbx.php(580): pfz_ipsec_status('1')
#1 /root/scripts/pfsense_zbx.php(1274): pfz_ipsec_ph1('1', 'status')
#2 {main}

![2022-08-24_101328](https://user-images.githubusercontent.com/111987531/186427603-41d07b23-1f00-4462-a39d-163372a06490.jpg)

**Comment by rbicelli** [comment]
Hello! Sorry busy here.
I have to check and test some PRs, move my develoment env to Zabbix 6 and release the template for pfsense 2.6/Zabbix 6.
Please wait some time :-)

**Comment by matthewknill** [comment]
Hi @rbicelli, just wondering if any progress has been made on Zabbix 6 support?
Thanks for the effort 😊

**Comment by rbicelli** [comment]
Hello,
the error @18vamberto posted isn't related to Zabbix 6. It is because in pfSense 2.6 the function get_ipsecifnum() no longer exists.
It is fixed now.
I confirm that the template is working in Zabbix 6.
