### ISSUE TITLE
phase 2 status doesn't work

### ISSUE THREAD

**Issue by gcortese22** [rbicelli/pfsense-zabbix-template#125]
Hi, I'm testing this template, I saw the script pfsense_zbx.php works as well about ipsec status IPsec phase 1.
The template doesn't have an item that prints the IPsec phase 2 status. I tried to create an item for this, but I didn't understand why the item value is 0 (Down) and if I try to put down the IPsec, I don't see change status.

Thanks in advance

**Comment by rbicelli** [comment]
As now, there are no phase 2 triggers. For how I used it since now (and I manage ten of ipsec tunnels) a trigger wired to phase 2 is not relevant.
