### ISSUE TITLE
OpenVPN Server 22.05-RELEASE

### ISSUE THREAD

**Issue by marcellomarques1986** [rbicelli/pfsense-zabbix-template#128]
Good afternoon.

I'm using the script for version 22.05-RELEASE.

Openvpn server returns zero for the tunnel status, but the tunnel is up.

Could you direct me to fix the problem?

**Comment by hvdhelm** [comment]
I believe the solution is the same as in issue #126

**Comment by marcellomarques1986** [comment]
It worked.

Thank you very much for your support.
