### ISSUE TITLE
Trigger issue on Pfsense version : Cannot evaluate expression: expected numeric token at

### ISSUE THREAD

**Issue by satanahell** [rbicelli/pfsense-zabbix-template#13]
Hello,

First, thanks for your perfect template and php file, this is exactly what i was looking for my homelab !

I got an error on the New version trigger and this is the details about it : 
_Cannot evaluate expression: expected numeric token at "2.4.5)<>(2.4.4_3)"._

I'm running a Zabbix LTS server with your recently updated template.
Pfsense (fresh install < 4d) is on 2.4.4_3 version with an update pending.

Thanks for your help.

**Comment by rbicelli** [comment]
Hi! Looks like logic operators in trigger expressions cannot be used to compare one item with another.
I have to move the ckeck inside the php script.
Thx

**Comment by satanahell** [comment]
you're welcome !

**Comment by rbicelli** [comment]
Fixed with latest commit.
