### ISSUE TITLE
Gateways Discovery: Gateway $2 Packet  Loss (MISS)

### ISSUE THREAD

**Issue by CarlosRafaelDuarte** [rbicelli/pfsense-zabbix-template#141]
Please, could you help me to identify the problem that the names of the items in relation to the gateway cannot get the real name, getting only the name of the variable.

  this happened after i updated zabbix5.0 to zabbix 6.0
  I will be very grateful for the help.

  I've already tried the templates from version 5 and version 6, both have problems with renaming gateway items

![image](https://user-images.githubusercontent.com/78601219/226105511-09bff35a-e3d7-479c-8f7e-da44b13f8d71.png)

![image](https://user-images.githubusercontent.com/78601219/226105530-0968a600-6512-46eb-a968-93b40da36ddf.png)

**Comment by fdorazio** [comment]
I've the same issue
+1
For the follow up

**Comment by rbicelli** [comment]
Hello,
It's something related to Macro Substitution in Zabbix 6. I'm also experiencing this issue. maybe someone with better knowledge in Zabbix may help.

**Comment by rbicelli** [comment]
Updated the template: looks like Zabbix dropped support for item key macro in item names.

see https://support.zabbix.com/browse/ZBXNEXT-4591
