### ISSUE TITLE
Pfsense 23.05.01 No Data from Interfaces

### ISSUE THREAD

**Issue by martinpetermichael** [rbicelli/pfsense-zabbix-template#148]
Hello,

thanks für this great Template! I've a Problem with teh Interface Data. All other Items are working fine - but i. E. net.if.in[vmx3,errors] has no Data (incomming / outgoing). Do you have any clue why, and how I can fix it?
Best regrads
Mic

**Comment by rbicelli** [comment]
Hello!
Network counters are taken from default zabbix agent. The discovery process is used for labeling the i9nterface internal name to "friendly" pfsense name (i.e. WAN->lagg1.127).
Upon discovery the counters are: `net.if.in[{#IFNAME},in]`, which translate after discovery to `net.if.in[lagg1.127]` for example. Check in your host item what discovery is creating, maybe in 23.05 something has changed in interface naming.

**Comment by martinpetermichael** [comment]
Hello,

in Zabbix (discovered Item) is: net.if.in[lagg0.4091,errors]
in pfsense the Interface is WAN Interface (wan, lagg0.4090, switchports: 1 9t 10t)
so this seems to be fine - but there is no value in it ...

**Comment by rbicelli** [comment]
Please, check latest template and let me know.
