### ISSUE TITLE
pfsense ver 23.05.1 doesn't work with speedtest cli 

### ISSUE THREAD

**Issue by TidalWave123** [rbicelli/pfsense-zabbix-template#151]
It looks like only python version 3.11 is installed and not python 3.8.

**Comment by GuillaumeHullin** [comment]
What do you get when running the command `speedtest` via Command Prompt?

I get the following error:

```
Retrieving speedtest.net configuration...
Testing from xxx (xxxx)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
ERROR: Unable to connect to servers to test latency.
```

Downloading the latest file https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py into the right plate bring up the same error.

I use pfSense 2.7.2-RELEASE (amd64) on FreeBSD 14.0-CURRENT.
