### ISSUE TITLE
speedtest with option --source doesn`t work

### ISSUE THREAD

**Issue by gus-it** [rbicelli/pfsense-zabbix-template#153]
Hello dear friend,
I'm using the pfSense template you provided on about 50 hosts and almost all of them work perfectly. However, the speedtest does not work on any of them. Today, carrying out some tests, I decided to remove the --source option from the script and it worked for me!
Is this option useful if my default gateway is a gateway group with all gateways in the system?
Does this option work for others and am I the one doing something wrong?
Best regards

Gustavo

**Comment by rbicelli** [comment]
Please check issue #119.
