### ISSUE TITLE
High packet Loss on WAN_DHCP6?

### ISSUE THREAD

**Issue by cwaddilove** [rbicelli/pfsense-zabbix-template#155]
I am struggling with this one item / trigger. It is always reporting a status of 3 which results in the high packet loss alert, but everything IPv6 works perfectly. I have an address on the firewall, my clients have an address, I can access IPv6 resources both from the clients and from the firewall. I've checked retransmitted packets for the last month of uptime and it's at 80. Any ideas on what to check next?

**Comment by rbicelli** [comment]
Gateway monitoring relies on pfSense gateway monitoring functions, which are responsibilities of dpinger.
Check your monitor IP, must be a valid IPv6 Address and non-ICMP blocking.
