### ISSUE TITLE
OpenSSLAsymmetricKey error 

### ISSUE THREAD

**Issue by tdutra0** [rbicelli/pfsense-zabbix-template#157]
I'm getting this error log from the script, Someone with the same case
Pfsense: 2.7.1-RELEASE

PHP ERROR: Type: 1, File: /root/scripts/pfsense_zbx.php, Line: 1237, Message: Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /root/scripts/pfsense_zbx.php:1237
Stack trace:
#0 /root/scripts/pfsense_zbx.php(1237): openssl_pkey_get_details(false)
#1 /root/scripts/pfsense_zbx.php(1278): pfz_get_cert_pkey_info('4')
#2 /root/scripts/pfsense_zbx.php(1646): pfz_get_ref_cert_algo('4')
#3 {main}

**Comment by fchicout** [comment]
Same problem as #163

**Comment by rbicelli** [comment]
Hopefully fixed with latest commit.
