### ISSUE TITLE
Monitoring Table Usage Count

### ISSUE THREAD

**Issue by GuillaumeHullin** [rbicelli/pfsense-zabbix-template#158]
This is not an issue but an idea.

I encountered a problem with my pfSense recently, where my table-entries hard limit was too low. In the GUI it's under "Firewall Maximum Table Entries" (https://docs.netgate.com/pfsense/en/latest/config/advanced-firewall-nat.html)

I was wondering if we could monitor the two items:
- Firewall Maximum Table Entries
- Table Usage Count

The trigger would be "Firewall Maximum Table Entries is too low" when Table Usage Count is more than half Maximum Table Entries.

The only place I could find the Table Usage Count is in the Update of pfBlocker (at the end).

```
pfSense Table Stats
-------------------
table-entries hard limit  2000000
Table Usage Count         420743
```

Anybody have an idea which command to use?

**Comment by rbicelli** [comment]
For example, for table usage, the syntax could be:
```
pfctl -s info | grep "current entries" | tr -s ' ' | cut -d " " -f4
``

**Comment by GuillaumeHullin** [comment]
> For example, for table usage, the syntax could be:
> 
> ```
> pfctl -s info | grep "current entries" | tr -s ' ' | cut -d " " -f4
> ```

Correct me if I'm wrong but this is the state table.

I went through the link you sent (btw, now I know what "pf" means in the name pfSense)

Is this command make a logical result for you?
```
pfctl -vvsTables | grep 'Addresses:   ' | awk '{sum += $2} END {print sum}'
```

**Comment by rbicelli** [comment]
Looks like that
```
pfctl -s info | grep "current entries" | tr -s ' ' | cut -d " " -f4
```
Outputs a value closer to this:
![immagine](https://github.com/rbicelli/pfsense-zabbix-template/assets/3899694/03dee712-04f2-44c7-aad5-a4d4c2d1c9d2)

```
pfctl -vvsTables | grep 'Addresses:   ' | awk '{sum += $2} END {print sum}'
```
outpust a value way higher than what is displayed in GUI (in my case 17281).

**Comment by rbicelli** [comment]
Sorry, I read with more attention what you wrote.
You want to monitor not only the state table but the whole table usage, so your one-liner return more meaningful value.
