### ISSUE TITLE
OpenVPN Client Status

### ISSUE THREAD

**Issue by emcgarcia101** [rbicelli/pfsense-zabbix-template#16]
Hi, everything works fine, except the OpenVPN Client Status...

I've tried on 3 setup, 2 on production and 1 Lab, the same issue on all of them.

The production Zabbix is 4.0 and the lab is 4.4, everything on lan network, no proxy, no encryption. Authentication using LDAP backend.

Sorry, my english is not the best...

**Comment by rbicelli** [comment]
Hi!
Are you monitoring a client which authenticaates to another pfsense in remote access/user auth mode or are you monitoring the server configured as user auth?

**Comment by emcgarcia101** [comment]
Hello!

Using remote access with user auth and ssl/tls certs, only one PfSense per site, the two production instances is on different companies, and the lab is on my home.

**Comment by rbicelli** [comment]
Please try running the script without arguments in pfSense shell and post the output. If posting here you should anonymize relevant data or send them to my mail address (is on top header of the script :))

**Comment by emcgarcia101** [comment]
Hi!

The return of the script, i used command "php pfsense_zbx.php" to run. 
One client connected at the moment with user: suporte.ti

[logzabbix.txt](https://github.com/rbicelli/pfsense-zabbix-template/files/4515643/logzabbix.txt)

**Comment by rbicelli** [comment]
What's your expected result? According to the template you should see the value
**OpenVPN Server {#NAME} Clients Connected** ramping to 1.

**Comment by emcgarcia101** [comment]
The Zabbix are not getting the information, below a screenshot.
![print pfsense](https://user-images.githubusercontent.com/64049524/80206574-f1064d00-8602-11ea-8b67-efb23ad8118e.PNG)

**Comment by rbicelli** [comment]
Sorry, but I still do not understand.

According to discovery rules the template is showing correctly the number of clients connected (the first value you see - Last Value 1, Change +1).
(BTW There's no implementation about which client is connected because to me is out of the scope of Zabbix. However making a new set of discovery rules for this is possible)

If you put to monitor the pfSense instance which is running as client you'll see a value like this:
![image](https://user-images.githubusercontent.com/3899694/80210649-63435580-8634-11ea-855f-521c09468388.png)
But you'll se this value only if you are initiating a tunnel **as client**.

**Comment by emcgarcia101** [comment]
exactly this implementation I was looking for, I will try the discovery rules and if successful I let you know

**Comment by kevendoliveira** [comment]
> Sorry, but I still do not understand.
> 
> According to discovery rules the template is showing correctly the number of clients connected (the first value you see - Last Value 1, Change +1).
> (BTW There's no implementation about which client is connected because to me is out of the scope of Zabbix. However making a new set of discovery rules for this is possible)
> 
> If you put to monitor the pfSense instance which is running as client you'll see a value like this:
> ![image](https://user-images.githubusercontent.com/3899694/80210649-63435580-8634-11ea-855f-521c09468388.png)
> But you'll se this value only if you are initiating a tunnel **as client**.

So as I understand it, the status "None" for the item Tunnel Status is normal, in case of using remote access mode is it better to disable the item?

**Comment by rbicelli** [comment]
> So as I understand it, the status "None" for the item Tunnel Status is normal, in case of using remote access mode is it better to disable the item?

Yes, it is normal. Even in pfSense GUI you won't see the VPN tunnel status when in user auth mode but only clients connected.

AFAIK in Zabbix you can't disable an item on a single element of a discovery rule. The only way I see for having this valued disabled (or hidden) is to split the  OpenVPN Server discovery in two parts:
- OpenVPN Servers P2P
- OpenVPN Servers User Auth
But the value itself is excluded from triggers, so I don't see a reason  for splitting discovery rules.

**Comment by rbicelli** [comment]
Hello! I released an optional template which monitors the connected clients. Please check it out.

**Comment by emcgarcia101** [comment]
You're the best!
