### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by conejero** [rbicelli/pfsense-zabbix-template#160]
I believe there is a typo in the readme, where it says

**/url/local/bin/php /root/scripts/pfsense_zbx.php speedtest_cron**
it shoule be
**/usr/local/bin/php /root/scripts/pfsense_zbx.php speedtest_cron**

**Comment by timotheeMM** [comment]
PR #162

**Comment by conejero** [comment]
Also ... 
pkg update && pkg install -y py38-speedtest-cli
the package has changed on latest pfsense CE (2.7.2). Suggest using pkg search speedtest first to get the right package.
At this moment: py311-speedtest-cli-2.1.3

PD: Great work, by the way! Thank you for this project. Its a great way of monitoring our pfsense farm.

**Comment by timotheeMM** [comment]
PR #164

**Comment by timotheeMM** [comment]
@rbicelli
This issue can be closed.
