### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /root/scripts/pfsense_zbx.php:817

### ISSUE THREAD

**Issue by riki976** [rbicelli/pfsense-zabbix-template#161]
I got this  Diagnostics[Crash Reporter]:

[27-Jan-2024 10:37:24 Europe/Madrid] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /root/scripts/pfsense_zbx.php:817
Stack trace:
#0 /root/scripts/pfsense_zbx.php(863): pfz_dhcp_get('failover')
#1 /root/scripts/pfsense_zbx.php(876): pfz_dhcp_check_failover()
#2 /root/scripts/pfsense_zbx.php(1091): pfz_dhcp('failover', NULL)
#3 {main}
  thrown in /root/scripts/pfsense_zbx.php on line 817

No FreeBSD crash data found.

I have pfsense 23.09.1-RELEASE (amd64)  and just downloaded last pfsense_zbx.php versión.

[23.09.1-RELEASE][admin@]/root: ls -alh /root/scripts/pfsense_zbx.php
-rw-r--r--  1 root wheel   47K Jan 27 10:37 /root/scripts/pfsense_zbx.php

**Comment by rbicelli** [comment]
Hopefully fixed with latest commit.
