### ISSUE TITLE
Packages Update Available

### ISSUE THREAD

**Issue by vasyna** [rbicelli/pfsense-zabbix-template#167]
Pfsense 2.7.2-RELEASE
zabbix-agent64 1.0.6

Zabbix server 6.4

actual template in zabbix and sh in pf.

After updating to the current template release, there was one unupdated package in the packages.
After updating the package, the trigger is not reset and the "Packages Needing Update" element returns the value "1". More than a week has passed.
![image](https://github.com/rbicelli/pfsense-zabbix-template/assets/4531827/759c7122-3603-4b8a-b42c-4d4fdb4613a0)

**Comment by openmilanese** [comment]
Add the new cron option:
/usr/local/bin/php /root/scripts/pfsense_zbx.php sysversion_cron

**Comment by vasyna** [comment]
thx. Although I added a task to cron when updating the script, apparently something went wrong.
