### ISSUE TITLE
Zabbix cannot obtain memory data

### ISSUE THREAD

**Issue by holychang** [rbicelli/pfsense-zabbix-template#168]
Many thanks to the author for developing a powerful script.

After I installed the zabbix agent, I could only obtain the status information of the CPU in the zabbix background, and there was no data in other fields such as memory information. Is it because the latest pfsense version does not support it? Or how I will troubleshoot this problem, hope to get your reply.

zabbix version: Zabbix 6.0.27.
pfSense version: 2.7.2-RELEASE (amd64)
![image](https://github.com/rbicelli/pfsense-zabbix-template/assets/26463789/98ba4e37-035e-4856-9ffe-e1457059f59a)

**Comment by da99Beast** [comment]
Did you follow all the install instructions?  My pfSense is working without issue showing this info and more.

**Comment by rbicelli** [comment]
Hi! memory is stock feature of Zabbix Freebsd Agent.
