### ISSUE TITLE
Unclosed error

### ISSUE THREAD

**Issue by perlporter** [rbicelli/pfsense-zabbix-template#169]
Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT amd64 1400094 #1 RELENG_2_7_2-n255948-8d2b56da39c: Wed Dec  6 20:45:47 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-CE-snapshots-2_7_2-main/obj/amd64/StdASW5b/var/jenkins/workspace/pfSense-CE-snapshots-2_7_2-main/sources/F

Crash report details:

PHP Errors:
[05-Apr-2024 11:17:43 America/Sao_Paulo] PHP Parse error:  Unclosed '{' on line 1138 in /root/scripts/pfsense_zbx.php on line 1145

No FreeBSD crash data found.

**Comment by rbicelli** [comment]
I assume this issue is something related to your pipeline. Please try to setup as written in readme and check if it works. If it doesn't work feel free to reopen the issue.
