### ISSUE TITLE
Multiple Gateways

### ISSUE THREAD

**Issue by cme-b2b** [rbicelli/pfsense-zabbix-template#171]
Hey there,
are multiple gateways supported at the moment? I have noticed that the status of "Gateways Status Raw" is "not supported" after installing the template and connecting to our firewall via passive agent and active checks. Did we maybe miss something in the setup process?
![image](https://github.com/rbicelli/pfsense-zabbix-template/assets/168761073/1c8d3d7f-1cf1-46b0-994a-31d0c6370f67)
The exclamation mark is stating "unsupported key item".
I hope you can help us out here. Many thanks in advance!
Best regards,
Chris

**Comment by rbicelli** [comment]
Hello,
looks like something related to your setup:

![immagine](https://github.com/rbicelli/pfsense-zabbix-template/assets/3899694/3cb74a57-bdbb-410b-9508-7fdc8ffba439)

The item is working as expected.

**Comment by cme-b2b** [comment]
Do you need speedtest installed to make it work? Could you please give me some pointers as to what could cause this?
I am running zabbix server 6.4.14 and pfsense version 23.09.1-RELEASE.
Thank you!

I have also noticed an inconsistency in documentation as in your readme it says that expected carp status = 0 means disabled, = 1 means master and = 2 means backup while the description in the macro in zabbix states 0 = master and 1 = slave.
