### ISSUE TITLE
Error when trying to apply template to Pfsense in Zabbix

### ISSUE THREAD

**Issue by cableguy103** [rbicelli/pfsense-zabbix-template#172]
when trying to apply the template to my Pfsense I get a error in Zabbix  "Cannot find host interface on "XXXXX" for item key "pfsense.value[cert_date,validFrom.max]"

All the certificates on the firewall are up to date and good.

Thanks

**Comment by rbicelli** [comment]
This issue is not related to template malfunction, but is Zabbix agent cofiguration issue. Please follow the installation guide in the README.
