### ISSUE TITLE
Zabbix 4.4

### ISSUE THREAD

**Issue by marcellomarques1986** [rbicelli/pfsense-zabbix-template#18]
When I use de script my zabbix server (OpenVPN server discovery) show me a message:

 Cannot create item: invalid value for preprocessing step #2: unmatched parentheses.

Can you help me with that error ?

![Screenshot - 2020-04-23T204335 529](https://user-images.githubusercontent.com/43152741/80160148-3eeb6880-85a3-11ea-9b35-39a3f82abbd9.png)

**Comment by rbicelli** [comment]
Check latest commit, there was a typo in php file

Il giorno ven 24 apr 2020 alle ore 01:45 marcellomarques1986 <
notifications@github.com> ha scritto:

**Comment by marcellomarques1986** [comment]
I have the new version, my brother was corrected that and sent the PULL REQUEST.

**Comment by marcellomarques1986** [comment]
Good evening.
I'm still trying to evolve with the template, I've already changed the php
but without success.
He continues to complain about the expression "Cannot create item: invalid value for preprocessing step # 2: unmatched parentheses."
![Screenshot - 2020-04-24T193808 410](https://user-images.githubusercontent.com/43152741/80262250-3c504800-8663-11ea-9a90-44ab92246217.png)

**Comment by rbicelli** [comment]
I think we were talking about different issues. I was referring to an error in php sources and you to Regexp issues.
The template isn't tested on Zabbix 4.4. The simplest way to make the template more compatible is to move the preprocessing inside the php script and expose directly an integer value to Zabbix

**Comment by marcellomarques1986** [comment]
Thanks for your helping @rbicelli !
It's working !

**Comment by rbicelli** [comment]
So you did any modification to the template for making it compatible with Zabbix 4.4 or is it working out of the box?

**Comment by marcellomarques1986** [comment]
I was unable to adjust the preprocessing with Regex, an alternative I adopted was to remove the Regex and create a JavaScript.

Pointing out that this part of was defined in:
if (value == "up") {
     return 1;
} else if (value == "down") {
     return 2;
} else if (value == "none") {
     return 3;
} else if (value == "reconnecting; ping-restart") {
     return 4;
} else {
     return 0;
}

I created new Trigger prototypes with the new values, the principle is working.

I would like to take advantage of the contact to congratulate you for the excellent work.

**Comment by rbicelli** [comment]
> I would like to take advantage of the contact to congratulate you for the excellent work.

Thanks!

BTW in order to mantain the compatibility between Zabbix 4.4 and 4.0 I'm moving the value preprocessing in the php script.
An update is coming soon.

**Comment by rbicelli** [comment]
When I say soon, I say today :-P.
Released latest commit which does the preprocessing in the php script.
You have to update the both template and the script.
If you don't want to reload the template it is sufficient to remove the value preprocessing in the discovery rules.
The New version available is fixed also.
