### ISSUE TITLE
WAN

### ISSUE THREAD

**Issue by eduardo-eller** [rbicelli/pfsense-zabbix-template#184]
How to use only the WAN monitoring part?
Without running the script containing all the other functions

PFSense version: 23.09.1-RELEASE (amd64)

**Comment by GuillaumeHullin** [comment]
I would assume that if you disable any unrelated cron task in pfSense and that you disable all the unrelated items in the Zabbix templates... then you would not have any running extra script. 

But the question is why would you want to that? If it's security... then also have a look at the User Parameters in your Zabbix Agent. Specifically restricting the AllowKey to the minimum and turning off AllowRoot maybe.
