### ISSUE TITLE
Cannot obtain "vfs.bufspace" system parameter

### ISSUE THREAD

**Issue by perlporter** [rbicelli/pfsense-zabbix-template#185]
78699:20240927:094646.325 active check "vm.memory.size[buffers]" is not supported: Cannot obtain "vfs.bufspace" system parameter: [12] Cannot allocate memory

Does anyone know what it could be?

**Comment by GuillaumeHullin** [comment]
Did you enabled the item manually? In the Zabbix template file, the item is disabled with the following note "Disk IO input cache. (Item disabled due to bug)"

**Comment by perlporter** [comment]
It was indeed enabled, and was properly disabled.
Thanks for your help.
