### ISSUE TITLE
Item became not supported: Cannot evaluate expression: cannot evaluate function last(): not enough data

### ISSUE THREAD

**Issue by ConorBeh** [rbicelli/pfsense-zabbix-template#2]
Hello,
I am using pfSense 2.4.4-p3 and Zabbix4.4. I cant seem to get any data from the pfSense. The following is outputted in my zabbix_server.log

44151:20191221:142609.363 item "pfsense-seattle:kt.mem.used" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
 44151:20191221:142614.694 item "pfsense-seattle:pfsense.mbuf.ptotal" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".
 44150:20191221:142617.276 item "pfsense-seattle:pfsense.states.pused" became not supported: Cannot evaluate expression: "Cannot evaluate function "last()": not enough data.".

**Comment by rbicelli** [comment]
Hello! I have tested this template only in Zabbix 4.0. Could you post some lines of your zabbix_agentd.log of your pfsense box?

**Comment by jmartens8855** [comment]
If you need more data on this, I am receiving the same (Zabbix 4.4, pfsense 2.4.4-p3).

**Comment by rbicelli** [comment]
Don't hava any Zabbix 4.4  for testing, we're tied to 4.0 LTS for now.
