### ISSUE TITLE
Openvpn client status

### ISSUE THREAD

**Issue by hidraulicChicken** [rbicelli/pfsense-zabbix-template#21]
Hey there,
Tried using your template and php, but encountered a problem. When I run php script.php 1 status, in most of the code the status is up, but in the end returns 0. Now when I looked at it I saw this
line 243 $value = pfz_valuemap("openvpn.server.client", $value);
line 457 case "openvpn.client.status":     
Am I wrong in assuming, that openvpn.server.client key should be openvpn.client.status instead?

**Comment by rbicelli** [comment]
Hi! I just did the corrections, please update to the latest commit.
Thx
