### ISSUE TITLE
OpenVPN Carp Status

### ISSUE THREAD

**Issue by zendzipr** [rbicelli/pfsense-zabbix-template#24]
When using PfSense in a redundant setup, not all OpenVPN instances are identified as enabled on CARP Slave = 0

I was able to identify a potential cause.

`$stopped_on_carp_slave = array("haproxy","openvpn.");`

changed to

`$stopped_on_carp_slave = array("haproxy","openvpn.","openvpn");`

And all OpenVPN instances now report as disabled on carp slave.

**Comment by rbicelli** [comment]
Thanks for your contribution, fixed in latest commit.
