### ISSUE TITLE
OpenVPN Server Status

### ISSUE THREAD

**Issue by zendzipr** [rbicelli/pfsense-zabbix-template#25]
Checking status of OpenVPN does not work for mode Remote Access ( SSL/TLS )(server_tls)

Current code in pfsense_zbx.php
 if ( ($server['mode']=="server_user") || ($server['mode']=="server_tls_user") ){

Modified code to

if ( ($server['mode']=="server_user") || ($server['mode']=="server_tls_user") || ($server['mode']=="server_tls")){

and the issue I was having appears resolved.

**Comment by rbicelli** [comment]
Thanks for your contribution, fixed in latest commit.
