### ISSUE TITLE
Zabbix 5.0

### ISSUE THREAD

**Issue by visionebc** [rbicelli/pfsense-zabbix-template#26]
Hi rbicelli, 

First of all thanks for share. 
I tried to make it work in Zabbix 5,  without succes.

![image](https://user-images.githubusercontent.com/34753443/82132179-3ae6eb00-97dd-11ea-8109-d5e47b8a1a6d.png)

Will you make a test in 5.0, in a short time?

Best regards,

**Comment by rbicelli** [comment]
Hi!
Sorry, don't have any Zabbix 5.0 test installation now. As soon I can play with it, I'llupdate the template.

**Comment by dragoangel** [comment]
I'm waiting for pfSense (FreeBSD) Zabbix 5.0 Proxy package to test this =(

**Comment by dragoangel** [comment]
@visionebc in your case it looks like your agent simply not connecting. Template doesn't matter. You can change your template to build-in FreeBSD template and I think you will see same. So double check  your Zabbix <--> pfSense Zabbix Agent connection and configuration. This can be firewall, dns, or PSK/SSL issues.

**Comment by dragoangel** [comment]
@rbicelli pfsense already support zabbix 5.0 agent and proxy =)

**Comment by rbicelli** [comment]
So have you tested the template an confirm that it works?

**Comment by eusouwilson** [comment]
Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 53 | Column: 69].
this error appeared when importing the template

**Comment by emcgarcia101** [comment]
Running on Zabbix 5.0, everything is normal! Remember the php script and advanced configs for the agent!

**Comment by jstride** [comment]
I can confirm that it works on Zabbix 5.0 too.
