### ISSUE TITLE
Gateway error with new line before status

### ISSUE THREAD

**Issue by antun3s** [rbicelli/pfsense-zabbix-template#28]
I don't know exactly why, but one of my server when i try get gateway status i receive data line:
```

none
```
To fix it i change a link on zabbix agent settins to use ` |   tail -1`
```
...
UserParameter=pfsense.value[*],/usr/local/bin/php /root/scripts/pfsense_zbx.php $1 $2 $3 | tail -1

```

I hope to help someone who has the same problem

**Comment by rbicelli** [comment]
Version of pfSense?

**Comment by antun3s** [comment]
All my pfsense are aupdaated (2.4.5-1), just one of then had this error. But, I fixed now.
