### ISSUE TITLE
Zabbix 4.4

### ISSUE THREAD

**Issue by jstride** [rbicelli/pfsense-zabbix-template#29]
I'm having an issue with zabbix 4.4 that it won't pull any values - it works fine with the default FreeBSD template but I get the following error: Cannot send request: wrong item type.

Have you seen this anywhere else?

**Comment by rbicelli** [comment]
Have you followed the installation instructions?

**Comment by jstride** [comment]
I did - I've just realised it's because the template uses active checks. I've changed that and it works fine.
