### ISSUE TITLE
What if my ovpn status was "reconnecting; ping-restart". 

### ISSUE THREAD

**Issue by firetxelo** [rbicelli/pfsense-zabbix-template#3]
Hello.

First, thank you for the amazing job. 

I saw in preprocessor of openvpn server status a code for up, down e none status. One of my tunnels got "reconnecting; ping-restart" status. How can I preprocess that to a value? 

Is this in php script?

For me an error appears 

"Preprocessing failed for: reconnecting; ping-restart
1. Result: reconnecting; ping-restart:up=1:down=0:none=0
2. Failed: cannot perform regular expression "(up|down|none)(?=.*:\1=(\d))" match for value of type "string": pattern does not match"

sorry about my english.

**Comment by rbicelli** [comment]
Hello! I  need to fix this in discovery rules.

**Comment by firetxelo** [comment]
OK... Thank you


Congratulations for the amazing job

**Comment by rbicelli** [comment]
Hello! Commited a fix for reconnecting-ping restart status. You have to re-import only the template file.
Please let me know if it works.

**Comment by firetxelo** [comment]
I add the changes in server side monitoring too and I changed the preprocessing to...

\1:up=1:down=0:none=0:reconnecting; ping-restart=3

In you xml was ...

\1:up=1:down=0:none=0:reconnecting; ping-restart=2

That works fine, but in my test I see a new status "waiting". Nevermind, now I know how to fix it.

Thank you so much for the job.

**Comment by rbicelli** [comment]
Added **reconnecting; ping-restart** and **waiting** to preprocessing and correspondant value mappings.
Thinking about moving away from preprocessing and return integer values from agent script.
