### ISSUE TITLE
Openvpn clients connected

### ISSUE THREAD

**Issue by fabianorbatista** [rbicelli/pfsense-zabbix-template#34]
Hello
After i updated my pfsense to 2.4.5-p1 i can no longer collect how many users are connected in vpn the intem to return the following error:

Value "Array" of type "string" is not suitable for value type "Numeric (float)"

root@sv-zabbix:/usr/home/ # zabbix_get -s 10.10.0.1 -p 10050 -k "pfsense.value[openvpn_servervalue,2,conns]"
Array

Can someone help me?
tanks

**Comment by rbicelli** [comment]
Please try to update the template to latest commit.
Thanks

**Comment by fabianorbatista** [comment]
HI,
I updated the template to the newest version but still keeps giving the same error message, I have an unliked and clean and imported the new template but it continued not collecting.

Value "Array" of type "string" is not suitable for value type "Numeric (unsigned)"

![Captura de tela de 2020-07-15 14-50-51](https://user-images.githubusercontent.com/17306508/87578334-a8fb4180-c6aa-11ea-96d2-c063cbb85c77.png)

**Comment by rbicelli** [comment]
It's strange ... My pfsense boxes are all on 2.4.5-p1 and never seen this error. Please try to execute the php script without arguments and check the logs of zabbix agent.
