### ISSUE TITLE
Last Version of PHP file

### ISSUE THREAD

**Issue by RagnarPino** [rbicelli/pfsense-zabbix-template#35]
Good Morning,

I use the previous php template in some pfsense boxes. I installed a new one this week and used the new php. All my gateways are alarmed as down. With data return 5 in zabbix. I went back to the old php and found that my links returned to receive 0 and returned to the UP status.

Best regards,

RagnarPino

**Comment by rbicelli** [comment]
Hi, have you updated the templates also? I removed value preprocessing in Zabbix.

**Comment by RagnarPino** [comment]
Hi! Thanks for the quick reponse,

I haven't updated the zabbix template. Maybe it is that. But in that case I will need to do this in several pfsense boxes at once. I will leave this update later. Even without updating the template, that was the only problem. The other datas were ok.

________________________________
De: Riccardo <notifications@github.com>
Enviado: quinta-feira, 16 de julho de 2020 10:30
Para: rbicelli/pfsense-zabbix-template <pfsense-zabbix-template@noreply.github.com>
Cc: Daniel Pino <danielpino@mcplusit.com>; Author <author@noreply.github.com>
Assunto: Re: [rbicelli/pfsense-zabbix-template] Last Version of PHP file (#35)


Hi, have you updated the templates also? I removed value preprocessing in Zabbix.
