### ISSUE TITLE
Openvpn: Server mode Peer-to-peer 

### ISSUE THREAD

**Issue by zeroone82** [rbicelli/pfsense-zabbix-template#36]
Hi

I just tried the template today and it works great. The only thing I have noticed so far it's that it will show a openvpn server as offline if it's in peer-to-peer mode. The status check seems to only check for the 3 remote access modes.

The check for peer-to-peer mode should be **p2p_shared_key** and **p2p_tls**

**Comment by rbicelli** [comment]
Hi, didn't notice.
I have some pfsense with p2p shared key (but not with p2p tls) and OpenVPN status is reported correctly, both in server and in client.
Peer to peer mode is reported as integer value then translated with value mapping.
Please post an example.
Thanks

**Comment by zeroone82** [comment]
Hi, I meant this check for server status:

```
// Get OpenVPN Server Value
function pfz_openvpn_servervalue($server_id,$valuekey){
     $servers = pfz_openvpn_get_all_servers();     
     
     foreach($servers as $server) {
          if($server['vpnid']==$server_id){
               $value = $server[$valuekey];
               if ($valuekey=="status") {
                    if ( ($server['mode']=="server_user") || ($server['mode']=="server_tls_user") || ($server['mode']=="server_tls") ){
                         if ($value=="") $value="server_user_listening";                    
                    }                    
               }
          }
     }
```

I added to more if case for p2p_tls and p2p_shared_key and it no longer shows my server as offline

**Comment by rbicelli** [comment]
This check is only for populate items when server is in user access mode.
If it's not the case the function will leave the value as is.
Please note that in case of p2_tls and p2p_shared_key the online status is triggered when tunnel is up, not when the service is listening.

**Comment by zeroone82** [comment]
Maybe I'm not understanding the trigger then, but on my p2p server it still seems to use that check on for the "OpenVPN Server is Down" trigger.

**Comment by TidalWave123** [comment]
I have this same issue. I'm on PFsense version 2.4.4. with Zabbix 5.0 server and Zabbix 5.0 client. Everything works great expect it's showing the OpenVPN server status as down. I am also using Peer to Peer (SSL/TLS)

I have a number of PFsense firewalls, and this particular firewall was the first one I ever setup. So I no longer use Peer to Peer and use the Remote Access options now a days.

**Comment by dani** [comment]
I've forked the pfsense_zbx.php script to handle some modifications I need. Here's what I've done to detect p2p_tls servers : https://git.fws.fr/fws/pfsense-zabbix/commit/a39483d77c472c9ae5d4eae592c631edaed9d28e
As it's p2p, I'm not interested in knowing the server is listening for incomming connections, I wan't to be sure the remote peer is connected. So I count the number of connected client and report up if it's > 0

**Comment by rbicelli** [comment]
Thanks, updated script with your modifications in latest commit.
Thanks for your contribution!
