### ISSUE TITLE
Triggers for Gateway Status based on third last value

### ISSUE THREAD

**Issue by jstride** [rbicelli/pfsense-zabbix-template#37]
I have a few gateway which ‘flap’ so I get a lot of triggers. I just wanted to check that the use of last(#3) was the intended behaviour in the triggers. 

I assumed that this meant the value had to be in that state for the last 3 readings but that is not the case reading the following:

The function last uses a different meaning for values when prefixed with the hash mark - it makes it choose the n-th previous value, so given the values 3, 7, 2, 6, 5 (from most recent to least recent), last(#2) would return 7 and last(#5) would return 5.

https://www.zabbix.com/documentation/current/manual/config/triggers/expression

**Comment by rbicelli** [comment]
Hi, it is not intentional. I misinterpreted the hash mark in last(). Honestly I find it a dumb behaviour.
Will fix the template.

**Comment by jstride** [comment]
Thanks, it’s not obvious - I thought exactly the same thing!

**Comment by rbicelli** [comment]
Fixed template file with last commit
