### ISSUE TITLE
Alert timing ?

### ISSUE THREAD

**Issue by killmasta93** [rbicelli/pfsense-zabbix-template#38]
Hi,
I was looking around the template and was getting a tad bit alerts but it goes away real quick, Would it be possible to check every 3mins? i checked on the discovery which is every 30 seconds, but not sure if that's the option
Thank you

**Comment by rbicelli** [comment]
Discovery timings were changed a couple commits ago, due to save resources on zabbix side. Feel free to change checks timings  to suit your needs.
