### ISSUE TITLE
Services not showing

### ISSUE THREAD

**Issue by TidalWave123** [rbicelli/pfsense-zabbix-template#39]
https://ibb.co/m0X8XPP
https://ibb.co/mDt5QBZ
https://ibb.co/pQSCDNf
https://ibb.co/VqS4Rm0

So for some reason the services feature isn't working for me on my negate SG-5100. All the other features work well but i'm not seeing any of the running services items getting any data. 

I can run zabbix_get -s 127.0.0.1 -k pfsense.value and I get the array field as seen in the photo and it lists all the services, but there isn't any data underneath them. 

zabbix_get -s 127.0.0.1 -k pfsense.value[services_value,dhcpd,status]

returns no match. 

I'm not that worried about the service status but would be nice. Thanks so much for all that you do. I'm running Zabbix 5.0 agent and Server. All the other features work great, just the services don't list for me! I have downloaded the php file as in the read me - hince all the other features work great.

**Comment by rbicelli** [comment]
Have you checked the timeout on zabbix agent settings?
Could you try to execute the script from console?

**Comment by rbicelli** [comment]
Please try the latest commit.
