### ISSUE TITLE
4 Discovery Rules Not Supported

### ISSUE THREAD

**Issue by ShaunLoureiro** [rbicelli/pfsense-zabbix-template#4]
Hi.
So i am running zabbix 4.2.8 and the pfSense box is on 2.4.4.
The install on the pfSense box was done by a colleague and i am trying to figure out if its an issue on my (Zabbix) side or if the installation was done incorrectly. 

4 of the discovery rules come up as unsupported and this is what they say.

(Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: '<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<link rel="dns-prefetch" href="https://github.githubassets.com">
<link rel="dn)

There is one entry i am getting for gateways and it says "Gateway Status Raw" and when i click on the history im getting the same error as above but its a FULL web page of code! :(

Now if i look at the latest data from the box i am getting info from the box but certain things such as gateways contain the same error. Also the green zabbix box does not get highlighted as green.

I am still pretty new to this all so sorry if its something small and stupid on my part but i would really appreciate some help!

Thanks :)

**Comment by firetxelo** [comment]
try to use zabbix-get or zabbix-agent -t to see what is returning to zabbix server and post here please

**Comment by ShaunLoureiro** [comment]
Hi Firetxelo. 

When i use the zabbix_get on the  Gateway Status Rawpfsense.value[gw_status].

I get a massive <!DOCTYPE html> file like i mentioned above. The file is WAY to big to post it all here.

**Comment by firetxelo** [comment]
sorry... I m not using the gateway monitoring. Others discovery rules have the same error?

**Comment by ShaunLoureiro** [comment]
What discovery rules are you using?

**Comment by ShaunLoureiro** [comment]
I get the same error for the pfsense.discovery[services] discovery rule :(

**Comment by firetxelo** [comment]
I m using openvpn discovery. That s working for me

**Comment by ShaunLoureiro** [comment]
![zabbix_get](https://user-images.githubusercontent.com/59390569/71721889-96689b80-2e2f-11ea-9358-720e742128fe.JPG)

**Comment by rbicelli** [comment]
> ![zabbix_get](https://user-images.githubusercontent.com/59390569/71721889-96689b80-2e2f-11ea-9358-720e742128fe.JPG)
It seems that you uploaded to pfsense the github page. You have to download only the php file or the zip containing the whole repository, then unzip the php file  in your pfsense box.

**Comment by ShaunLoureiro** [comment]
Hi 
Thanks for the reply. WOW...... Need to check with the guy that did the install and see what he uploaded.
