### ISSUE TITLE
Temp reading with netgate appliances. 

### ISSUE THREAD

**Issue by TidalWave123** [rbicelli/pfsense-zabbix-template#40]
For Netgate appliances they offer a temp reading. 

So I've added the user agents 

UserParameter=temperature0,sysctl -n dev.cpu.0.temperature
UserParameter=temperature1,sysctl -n dev.cpu.1.temperature

Which returns a text value of 32.0C. I'll try to make a custom trigger for it. Just wanted other netgate users to know.

**Comment by keentonsas** [comment]
Hi there,

For the text value, you can strip the `C` with preprocessing in Zabbix (`Right Trim: C`), then you should be able to store it as a _float_.

For CPU temperature in general, I think we need to discover how many cores are available, or simply calculate an average value for all cores before sending it to Zabbix.

Bye.

**Comment by rbicelli** [comment]
I think creating proper discovery rules is the best way to achieve cpu temps. From the template design perspective is preferable to read temperatures from pfsense php function library.
Will look into it as soon as I make the next review
