### ISSUE TITLE
Gateway always 5 ('Down')

### ISSUE THREAD

**Issue by sgi-ch** [rbicelli/pfsense-zabbix-template#42]
Hi Riccardo

We've a pfSense Cluster and we did turn on the Option «Disable Gateway Monitoring». With that, the Gateway has the Status «Online (unmonitored)». Now we did some adjustments before using your Template and disabled the option «Disable Gateway Monitoring». So pfSense does active Ping its Gateway.

But your Template/Script does still show the Gateway as «Down» (5). I did not yet have the time to search the issue and check your Script. What i was able to test is, with the Template of Leonardo (https://github.com/lndgoncalves/zabbix-pfsense-gateway) i was successful - with the Template of Leonardo, the Gateway-Status is always correct.

Maybe you have any idea.

> 2.4.5-RELEASE-p1 (amd64)
> built on Tue Jun 02 17:51:17 EDT 2020
> FreeBSD 11.3-STABLE

**Comment by rbicelli** [comment]
The "internal" value mapping for gateway status is:
```   
$valuemap = array(
                         "none" => "0",
                         "loss" => "1",
                         "highdelay" => "2",
                         "highloss" => "3",
                         "force_down" => "4",
                         "down" => "5");

```
This basically makes the mapping string:integer internally, avoiding using item preprocessing on zabbix side.
I think is missing mapping for unmonitored status. Could you post the value of item "Gateways RAW Status" with unmonitored gateway in place?
Thanks

**Comment by sgi-ch** [comment]
Our Gateway is named/labled with `VTX`. Before it was `VTX.None`, not its only `VTX.` (including the dot).

**Comment by rbicelli** [comment]
Please try via pfsense cli:
```
php /path/to/script/pfsense_zbx.php gw_value VTX status
```
And post the output. I assume it will display 5 or empty.

**Comment by sgi-ch** [comment]
`[2.4.5-RELEASE][user@pfsense]/root: /usr/local/bin/php /root/scripts/pfsense_zbx.php gw_value VTX status`
`0`

![image](https://user-images.githubusercontent.com/42451338/91083876-561e8d80-e64b-11ea-9f97-39e6c0cc0b60.png)

**Comment by rbicelli** [comment]
Seems quite strange. In the discovery items, gateway status, do you have some value preprocessing in place?

**Comment by sgi-ch** [comment]
Yes, those where in the Template.

![image](https://user-images.githubusercontent.com/42451338/91168856-a0008580-e6d6-11ea-873e-2312b7662d0e.png)

**Comment by rbicelli** [comment]
Recently (more than a month ago) I've changed the template and removed the value preprocessing (preprocessing done in php script).
Maybe you are using an old version of the template or I've updated the repo with wrong template.
Try removing preprocessing and please update the template to the current master release.

**Comment by sgi-ch** [comment]
Ah sorry, did not get that and did not compare. I'll update the Template and update the issue

**Comment by sgi-ch** [comment]
Yes, with the new Version, everything is working. Thanks for the Support!

**Comment by rbicelli** [comment]
> Yes, with the new Version, everything is working. Thanks for the Support!

You are welcome!

**Comment by antun3s** [comment]
Thanks @rbicelli it's work for me
