### ISSUE TITLE
List of service which are stopped on CARP Slave

### ISSUE THREAD

**Issue by sgi-ch** [rbicelli/pfsense-zabbix-template#43]
You did wrote on your Script the following

> //List of service which are stopped on CARP Slave.
> //For now this is the best way i found for filtering out the triggers
> //Waiting for a way in Zabbix to use Global Regexp in triggers with items discovery

Here an Input/Idea. Don't know if you like to use, because it needs some little work by the user, but i think it's more flexible then hard in the Code.

On your Template you add a Macro called, as an example, which has the value '1' (or '0')
> {$CARP.SLAVE.SERVICES}

On your Trigger for the Services, you adding to the expression
> and ({$CARP.SLAVE.SERVICES:"{#NAME}"}=1

If you now add the Template to your Slave-Host, you can add the following Macros and no Trigger should be fired. You can also use it on the Master (and Slave) if you did stop any Service (for whatever reason) manually and no Trigger should be fired.
> {$CARP.SLAVE.SERVICES:"haproxy"}
> {$CARP.SLAVE.SERVICES:"openvpn."}
> {$CARP.SLAVE.SERVICES:"openvpn"}

*** Would be better to add also the Name of the Services instead only of the Description. Because with that, the Macro which needs to be added is shorter and more readable.

**Comment by rbicelli** [comment]
Hi! That's a good Idea. I will look into it ASAP!

**Comment by Phurion** [comment]
I like this idea, I just submitted a bug for a service that should be stopped on a carp slave #51

**Comment by rbicelli** [comment]
I'm trying to implement it, but I found a caveat:
with openvpn, for example, in which you could have different servers named openvpn.**servername**, the user must add every openvpn server in the macro section.
Would it be feasible having an hardcoded part in the scripts and a part defined in macro?
i.e.
`and (({$CARP.SLAVE.SERVICES:"{#NAME}"}=1) or  ({Template pfSense Active:pfsense.value[service_value,{#SERVICE},run_on_carp_slave].last()}=1))`

**Comment by sgi-ch** [comment]
in my opinion, users which can work with templates, should be able to do that and you would have the biggest flexibility, because you can define it per each OpenVPN Server. But thats my opinion :)

**Comment by rbicelli** [comment]
For example, in my setups, VPN servers are active on both firewalls, because they are listening on localhost and there's a NAT rule from carp VIP to localhost.
Will try the macro route :-)

**Comment by rbicelli** [comment]
I spent many hours trying different solutions but with no results.
I thing adding one macro per service is  little tedious task for the user and editing the hardcoded part in php script is faster.
There's some people asking Zabbix developers tu support host macros in item parameters. With this feature defining services stopped on carp slave will be easy as creating a macro like this:
`{$SERVICES_STOPPED_ON_CARP_SLAVE}="haproxy,openvpn.,openvpn"`
So, until Zabbix doen't add this feature, will keep the hardcoded values.

**Comment by sgi-ch** [comment]
thanks for the update!
