### ISSUE TITLE
Description in xml causes errors 

### ISSUE THREAD

**Issue by daancee** [rbicelli/pfsense-zabbix-template#44]
in template_pfsense_active.xml the text within <description></description> is causing errors in Zabbix 5.0.
When shortening the text the import went smoothly.

Original (failed):
            <description>Active template for pfsense, requires pfsense_zbx.php installed to pfSense Box.&#13;
Version 1.0.1&#13;
&#13;
https://github.com/rbicelli/pfsense-zabbix-template</description>

Changed to (imported successfully): 
            <description>Active template for pfsense</description>

**Comment by rbicelli** [comment]
Please check if the problems is the length of text or punctuation. I don't currently have a Zabbix 5 installation for test so I have to rely on you. Thanks

**Comment by daancee** [comment]
Hi Riccardo,

The error said: zabbix Invalid parameter "/source": invalid byte sequence
in UTF-8.
Seems to be the special character being used is causing the nuisance.

Goog luck with testing.

Cheers,
Daniel

Op vr 28 aug. 2020 om 13:28 schreef Riccardo <notifications@github.com>:

**Comment by rbicelli** [comment]
Current template imorts fine in Zabbix 5.
