### ISSUE TITLE
False alarms?

### ISSUE THREAD

**Issue by farzadha2** [rbicelli/pfsense-zabbix-template#45]
Hi,
Currently installed on a few pfSense boxes but i keep getting false alarms, maybe possible changing to check every 5mins?
I normally get alerts saying WAN gateway down but 3 seconds later it shows resolved
Then i check pfSense on the quality of the gateway and didn't show anything odd.
Thank you

**Comment by rbicelli** [comment]
Hi! Of course you can try to raise the time interval between gateways status checks (in templates, discovery rules related to gateways).
Please let me know if raising solves the issue.
I have few boxes (approx 5) and everything seems fine.

**Comment by farzadha2** [comment]
Thanks for the reply,
so i configured to update interval to 300s which is 5 mins but odd that i keep getting the alert see pictures

![image](https://user-images.githubusercontent.com/62571297/92631274-bee64680-f296-11ea-8f8b-7e892c705193.png)

![image](https://user-images.githubusercontent.com/62571297/92631653-42a03300-f297-11ea-9c8e-e9b34f7cd557.png)

![image](https://user-images.githubusercontent.com/62571297/92632693-bc382100-f297-11ea-96c3-c990c96782bb.png)

![image](https://user-images.githubusercontent.com/62571297/92632899-ca863d00-f297-11ea-95d0-cf249e2d01ca.png)

Thank you

**Comment by rbicelli** [comment]
I found that template published has "debug intervals": maybe discovery queries, which are sent every 30 seconds, are causing problems. Please try to set every discovery interval at leas to 600 seconds an see if it helps.
One some boxes (I use both proxy and agent package on pfsense, so pfsense acts as zabbix proxy for the whole branch office) I noticed some gateway wrongly reported down, but not flapping, solved restarting agent and proxy services after changing discovery and item sending intervals to a reasonable value.

**Comment by farzadha2** [comment]
thanks for the reply, as for the discovery interval on the zabbix server? and after changing it restart the service the zabbix service on pfsense?
Thank you

**Comment by rbicelli** [comment]
Please check latest commit, made some change to gateways.

**Comment by farzadha2** [comment]
thanks for the reply will try it out and post back
