### ISSUE TITLE
Wrong template group name

### ISSUE THREAD

**Issue by yurtesen** [rbicelli/pfsense-zabbix-template#46]
The openvpn template has group name with lowercase `d`
```
            <groups>
                <group>
                    <name>Templates/Network devices</name>
                </group>
            </groups>
```
It causes a new group to be created.
![image](https://user-images.githubusercontent.com/1926599/92688468-0d065300-f346-11ea-8095-800e71b40122.png)

**Comment by rbicelli** [comment]
Fixed
