### ISSUE TITLE
Causes 50% CPU usage

### ISSUE THREAD

**Issue by yurtesen** [rbicelli/pfsense-zabbix-template#47]
On a system with many OpenVPN tunnels and servers, and many interfaces and VLANs. This increases load from 1% to 50%
It is not usable like this unfortunately...

**Comment by rbicelli** [comment]
Please try to raise the interval of item checks in discovery rules.

**Comment by rbicelli** [comment]
I checked the template and it seems I didn't corrected some check intervals after tests.
Now I raised the discovery intervals and some items check (i.e. gateway status and vpn tunnel status every 30 seconds are a bit aggressive) and checking CPU utilization.
Will upload an update soon.

**Comment by yurtesen** [comment]
There are also other people at zabbix share site which commented about high CPU use.

I think the checks are just taking too much CPU time. If you increase the interval, the high CPU usage will happen with longer intervals. Yes it is an improvement that high CPU usage will not be constant, but not a good solution overall. I feel the checks must be somehow simplified to not use so much processing power

Unfortunately I do not have time to go back and check this. So I won't be able to test it again... So I do not know how else I can contribute right now.

**Comment by rbicelli** [comment]
Sorry but I don't check Zabbix share as regular basis.
You can help trying to determine which check is causing high CPU usage.
