### ISSUE TITLE
Zabbix 5.0 and PFSense 2.4

### ISSUE THREAD

**Issue by ScooterNC** [rbicelli/pfsense-zabbix-template#48]
I have followed your instructions and used the Zabbix Agent 5.0 on PFSense.  I cannot get it to work.  If I use the FreeBSD, it connects.

**Comment by rbicelli** [comment]
Please check issue #26 and follow the installation guide.

**Comment by ScooterNC** [comment]
I did check that issue before opening this one.  Why did you close this?

**Comment by rbicelli** [comment]
> Why did you close this?
Sorry, pushed close and comment instead of Comment.

Please double-check the configuration and post details (screenshots, log, cli results) if you're seeking help.

**Comment by ScooterNC** [comment]
No worries.  I have doubled check everything and it follows the instructions.  I will get you the screenshots and captures

**Comment by ScooterNC** [comment]
<img width="1404" alt="Zabbix FreeBSD" src="https://user-images.githubusercontent.com/71102830/92938541-aacb5200-f41a-11ea-9ae5-bfc7f1058372.png">
<img width="1139" alt="PFSense Agent 3" src="https://user-images.githubusercontent.com/71102830/92938542-ab63e880-f41a-11ea-8726-c40e243b7b76.png">
<img width="1154" alt="PFSense Agent 2" src="https://user-images.githubusercontent.com/71102830/92938543-ab63e880-f41a-11ea-9d04-41fae102d17b.png">
<img width="1142" alt="PFSense Agent" src="https://user-images.githubusercontent.com/71102830/92938545-ab63e880-f41a-11ea-8c52-25ffa4434c7b.png">
<img width="1369" alt="Zabbix pfsense active" src="https://user-images.githubusercontent.com/71102830/92938547-abfc7f00-f41a-11ea-9bd5-55a3e35fabe3.png">
Here are the screenshots.  The FreeBSD one shows connection is good so it is something else

**Comment by rbicelli** [comment]
Have you tried to run the php script via pfsense cli?
Does it execute without errors?

**Comment by ScooterNC** [comment]
I get permission denied.  Any ideas?  I am logged in as admin

**Comment by ScooterNC** [comment]
I had to change the permissions of the file and now I get:
./pfsense_zbx.php: cannot open ?php: No such file or directory
./pfsense_zbx.php: /COPYRIGHT: Permission denied
./pfsense_zbx.php: pfsense_zbx.php: not found
./pfsense_zbx.php: Version: not found
./pfsense_zbx.php: 6: Syntax error: newline unexpected (expecting word)

**Comment by rbicelli** [comment]
You need to login as root via ssh or in console.

**Comment by ScooterNC** [comment]
I am logged in as root, same issue.

./pfsense_zbx.php: cannot open ?php: No such file or directory
./pfsense_zbx.php: /COPYRIGHT: Permission denied
./pfsense_zbx.php: pfsense_zbx.php: not found
./pfsense_zbx.php: Version: not found
./pfsense_zbx.php: 6: Syntax error: newline unexpected (expecting word)

**Comment by rbicelli** [comment]
try:

/usr/local/bin/php ./pfsense_zbx.php

**Comment by ScooterNC** [comment]
It runs doing it like that.  

[2.4.5-RELEASE][root@firewall.kreitler.us]/root/scripts: /usr/local/bin/php ./pfsense_zbx.php
OPENVPN Servers:
Array
(
    [0] => Array
        (
            [port] => 443
            [mode] => server_tls_user
            [name] => Server TCP4:443
            [conns] => Array
                (
                )

            [vpnid] => 1
            [mgmt] => server1
        )

)
-------------------
OPENVPN Clients:
Array
(
)
-------------------
Network Interfaces:
Array
(
    [WAN] => Array
        (
            [hwif] => WAN
            [enable] => 1
            [if] => WAN
            [status] => up
            [macaddr] => 00:0c:29:3c:be:98
            [mtu] => 1500
            [ipaddr] => 75.163.53.223
            [subnet] => 255.255.255.0
            [linklocal] => fe80::20c:29ff:fe3c:be98%WAN
            [ipaddrv6] => 
            [subnetv6] => 
            [inerrs] => 0
            [outerrs] => 0
            [collisions] => 0
            [inbytespass] => 2956530787834
            [outbytespass] => 552373583442
            [inpktspass] => 2273446883
            [outpktspass] => 1199908071
            [inbytesblock] => 424839592
            [outbytesblock] => 808
            [inpktsblock] => 33419346
            [outpktsblock] => 16
            [inbytes] => 2956530787834
            [outbytes] => 552373583442
            [inpkts] => 2273446883
            [outpkts] => 1199908071
            [dhcplink] => up
            [media] => autoselect
            [gateway] => 75.163.53.254
            [gatewayv6] => 
        )

    [LAN] => Array
        (
            [hwif] => LAN
            [enable] => 1
            [if] => LAN
            [status] => up
            [macaddr] => 00:0c:29:3c:be:b6
            [mtu] => 1500
            [ipaddr] => 192.168.250.1
            [subnet] => 255.255.255.0
            [linklocal] => fe80::20c:29ff:fe3c:beb6%LAN
            [ipaddrv6] => 
            [subnetv6] => 
            [inerrs] => 0
            [outerrs] => 0
            [collisions] => 0
            [inbytespass] => 556172352055
            [outbytespass] => 3125309395339
            [inpktspass] => 1304989172
            [outpktspass] => 2523900084
            [inbytesblock] => 330328177
            [outbytesblock] => 2771620
            [inpktsblock] => 2483571
            [outpktsblock] => 34660
            [inbytes] => 556172352055
            [outbytes] => 3125309395339
            [inpkts] => 1304989172
            [outpkts] => 2523900084
            [media] => autoselect
        )

    [GUEST] => Array
        (
            [hwif] => Guest
            [enable] => 1
            [if] => Guest
            [status] => up
            [macaddr] => 00:0c:29:3c:be:a2
            [mtu] => 1500
            [ipaddr] => 192.168.245.1
            [subnet] => 255.255.255.240
            [linklocal] => fe80::20c:29ff:fe3c:bea2%Guest
            [ipaddrv6] => 
            [subnetv6] => 
            [inerrs] => 0
            [outerrs] => 0
            [collisions] => 0
            [inbytespass] => 319732659
            [outbytespass] => 11218603007
            [inpktspass] => 3770066
            [outpktspass] => 8161769
            [inbytesblock] => 2735740
            [outbytesblock] => 0
            [inpktsblock] => 45472
            [outpktsblock] => 0
            [inbytes] => 319732659
            [outbytes] => 11218603007
            [inpkts] => 3770066
            [outpkts] => 8161769
            [media] => autoselect
        )

    [IOT] => Array
        (
            [hwif] => IoT
            [enable] => 1
            [if] => IoT
            [status] => up
            [macaddr] => 00:0c:29:3c:be:ac
            [mtu] => 1500
            [ipaddr] => 192.168.254.1
            [subnet] => 255.255.255.224
            [linklocal] => fe80::20c:29ff:fe3c:beac%IoT
            [ipaddrv6] => 
            [subnetv6] => 
            [inerrs] => 0
            [outerrs] => 0
            [collisions] => 0
            [inbytespass] => 202677887548
            [outbytespass] => 16944929081
            [inpktspass] => 343188643
            [outpktspass] => 197769564
            [inbytesblock] => 113215087
            [outbytesblock] => 960
            [inpktsblock] => 1203493
            [outpktsblock] => 6
            [inbytes] => 202677887548
            [outbytes] => 16944929081
            [inpkts] => 343188643
            [outpkts] => 197769564
            [media] => autoselect
        )

)
Array
(
    [0] => LAN
    [1] => WAN
    [2] => Guest
    [3] => IoT
    [4] => lo0
    [5] => enc0
    [6] => pfsync0
    [7] => pflog0
    [8] => ovpns1
)
Array
(
    [wan] => wan
    [lan] => lan
    [opt1] => opt1
    [opt2] => opt2
)
-------------------
Services: 
Array
(
    [0] => Array
        (
            [name] => vmware-guestd
            [rcfile] => vmware-guestd.sh
            [custom_php_service_status_command] => mwexec("/usr/local/etc/rc.d/vmware-guestd status") == 0;
            [description] => VMware Guest Daemon
        )

    [1] => Array
        (
            [name] => vmware-kmod
            [rcfile] => vmware-kmod.sh
            [custom_php_service_status_command] => mwexec("/usr/local/etc/rc.d/vmware-kmod status") == 0;
            [description] => VMware Kernel Modules
        )

    [2] => Array
        (
            [name] => bandwidthd
            [rcfile] => bandwidthd.sh
            [executable] => bandwidthd
            [description] => BandwidthD bandwidth monitoring daemon
        )

    [3] => Array
        (
            [name] => zabbix_agentd
            [rcfile] => zabbix_agentd.sh
            [executable] => zabbix_agentd
            [description] => Zabbix Agent Host Monitor Daemon
        )

    [4] => Array
        (
            [name] => unbound
            [description] => DNS Resolver
        )

    [5] => Array
        (
            [name] => ntpd
            [description] => NTP clock sync
        )

    [6] => Array
        (
            [name] => syslogd
            [description] => System Logger Daemon
        )

    [7] => Array
        (
            [name] => dhcpd
            [description] => DHCP Service
        )

    [8] => Array
        (
            [name] => dpinger
            [description] => Gateway Monitoring Daemon
        )

    [9] => Array
        (
            [name] => miniupnpd
            [description] => UPnP Service
        )

    [10] => Array
        (
            [name] => ipsec
            [description] => IPsec VPN
        )

    [11] => Array
        (
            [name] => sshd
            [description] => Secure Shell Daemon
        )

    [12] => Array
        (
            [name] => openvpn
            [mode] => server
            [id] => 0
            [vpnid] => 1
            [description] => OpenVPN server: 
        )

)

**Comment by ScooterNC** [comment]
I would ask that once we figure this out if we can delete the posts with my info in it that would be great

**Comment by rbicelli** [comment]
It seems is quite ok.
Did you put the script in /root/scripts directory?
If the script is in another directory you have to adjust the settings in zabbix agent configuration.

Check the zabbix agent logs also.

**Comment by ScooterNC** [comment]
it is there:

[2.4.5-RELEASE][root@firewall.kreitler.us]/root/scripts: ls
pfsense_zbx.php
[2.4.5-RELEASE][root@firewall.kreitler.us]/root/scripts: pwd
/root/scripts

how do I check the agent logs?

**Comment by rbicelli** [comment]
They are usually located in /var/log/zabbix_agentd.log
Maybe in pfsense they are located in a different path

**Comment by ScooterNC** [comment]
Here are the logs.
25500:20200911:094154.244 Starting Zabbix Agent [firewall.kreitler.us]. Zabbix 5.0.1 (revision c2a0b03480).
 25500:20200911:094154.244 **** Enabled features ****
 25500:20200911:094154.244 IPv6 support:          YES
 25500:20200911:094154.244 TLS support:           YES
 25500:20200911:094154.244 **************************
 25500:20200911:094154.244 using configuration file: /usr/local/etc/zabbix44/zabbix_agentd.conf
 25500:20200911:094154.244 agent #0 started [main process]
 25879:20200911:094154.244 agent #1 started [collector]
 26105:20200911:094154.245 agent #2 started [listener #1]
 26172:20200911:094154.245 agent #3 started [listener #2]
 26242:20200911:094154.245 agent #4 started [listener #3]
 25500:20200911:163813.339 Got signal [signal:15(SIGTERM),sender_pid:46040,sender_uid:0,reason:65537]. Exiting ...
 25500:20200911:163813.341 Zabbix Agent stopped. Zabbix 5.0.1 (revision c2a0b03480).
 47123:20200911:163818.414 Starting Zabbix Agent [firewall.kreitler.us]. Zabbix 5.0.1 (revision c2a0b03480).
 47123:20200911:163818.415 **** Enabled features ****
 47123:20200911:163818.415 IPv6 support:          YES
 47123:20200911:163818.415 TLS support:           YES
 47123:20200911:163818.415 **************************
 47123:20200911:163818.415 using configuration file: /usr/local/etc/zabbix44/zabbix_agentd.conf
 47123:20200911:163818.415 agent #0 started [main process]
 47388:20200911:163818.415 agent #1 started [collector]
 47698:20200911:163818.415 agent #2 started [listener #1]
 47729:20200911:163818.416 agent #3 started [listener #2]
 48038:20200911:163818.416 agent #4 started [listener #3]
 47123:20200911:163959.844 Got signal [signal:15(SIGTERM),sender_pid:3838,sender_uid:0,reason:65537]. Exiting ...
 48038:20200911:163959.844 failed to accept an incoming connection: select() failed: [4] Interrupted system call
 47123:20200911:163959.845 Zabbix Agent stopped. Zabbix 5.0.1 (revision c2a0b03480).

**Comment by ScooterNC** [comment]
Looks like when I update the config for the agent it stops and restarts so this log isn't very useful

**Comment by ScooterNC** [comment]
I changed the template to FreeBSD and it went green and that log didn't show anything

**Comment by ScooterNC** [comment]
One thing I did notice is that the FreeBSD template reference Template Module Zabbix agent.  So I have added that template too and will let you know if anything changes

**Comment by rbicelli** [comment]
In my setups I've never linked other templates besides this.
Please note this is an active template and some requirements must be met in order to perform active checks.
I suggest you to try to reconfigure everything from scratch

**Comment by ScooterNC** [comment]
so I tried that to no avail.  I looked at the agent config and it doesnt have any of the user parameters.  Shouldnt this file have them?

**Comment by ScooterNC** [comment]
I uninstalled 5 and installed 4.4 and it shows in the config file now.  I will let you know if it starts working.

**Comment by ScooterNC** [comment]
Nope it shows red for ZBX. Any other ideas?  Don’t know if this makes a difference but this is a VM on ESXi

**Comment by ScooterNC** [comment]
You can close this.  Disappointing I cant use it but oh well.

**Comment by rbicelli** [comment]
> You can close this. Disappointing I cant use it but oh well.

I'm sorry but looking to your configuration page in pfsense seems you didn't filled the "Server Active" field, which has to match the zabbix server name defined in zabbix configuration.

See https://www.zabbix.com/documentation/current/manual/appendix/items/activepassive

**Comment by ScooterNC** [comment]
That worked.  I wasnt aware that I had to do that.  I am not very well versed in Zabbix but I really appreciate your help.
