### ISSUE TITLE
Service status check issue

### ISSUE THREAD

**Issue by msultanov** [rbicelli/pfsense-zabbix-template#49]
Hello,

Thank you for your great work on this monitoring script. I found a small mistake in the function **pfz_service_value** that affects services with the space in the names, for example, FRR package.
```
    [1] => Array
        (
            [name] => FRR zebra
            [rcfile] => frr.sh
            [executable] => zebra
            [description] => FRR core/abstraction daemon
        )

    [2] => Array
        (
            [name] => FRR staticd
            [rcfile] => frr.sh
            [executable] => staticd
            [description] => FRR static route daemon
        )

    [3] => Array
        (
            [name] => FRR bfdd
            [rcfile] => frr.sh
            [executable] => bfdd
            [description] => FRR BFD daemon
        )

    [4] => Array
        (
            [name] => FRR bgpd
            [rcfile] => frr.sh
            [executable] => bgpd
            [description] => FRR BGP routing daemon
        )

    [5] => Array
        (
            [name] => FRR ospfd
            [rcfile] => frr.sh
            [executable] => ospfd
            [description] => FRR OSPF routing daemon
        )

    [6] => Array
        (
            [name] => FRR ospf6d
            [rcfile] => frr.sh
            [executable] => ospf6d
            [description] => FRR OSPF6 routing daemon
        )
```

When Zabbix discover the items using another function **pfz_services_discovery**, you are replacing space with the "__"
`$json_string .= '{"{#SERVICE}":"' . str_replace(" ", "__", $service['name']) . $id . '"'; `

Then, when Zabbix checking service status, you are trying to replace "__" with the spaces in the original service name and comparing it with the name from Zabbix with the "__", which is wrong.
```
foreach ($services as $service){
          $namecfr=str_replace("__"," ",$service["name"]);
...
          if ($namecfr == $name){
...

```

The replace should be in the same way as in the service discovery function. Could you please fix this in your PHP file. 
`$namecfr=str_replace(" ", "__", $service["name"]);`
Thanks a lot again!!

**Comment by rbicelli** [comment]
Sorry but I don't understand the point.
In the discovery function " " is replaced with "__". So if your service name is "TFRR bfdd" it became "TFRR__bfdd" and the consequent item name is FRR__bfdd.
When checking status zabbix call the script passing as argument "FRR__bfdd" (the item name). So, for reading through pfsense services array, I have to do the replacement backwards, replacing "__" with " ".

**Comment by msultanov** [comment]
You are right in your explanation. But in the code, when you are doing backwards replacing you are replacing the original service name, not the name that passed from Zabbix ))

```
function pfz_service_value($name,$value){
     $services = get_services();  ///Here you geting all the services from pfSense
     $stopped_on_carp_slave = array("haproxy","openvpn.","openvpn");
     foreach ($services as $service){ /// Here you are iterating through the services
          $namecfr=str_replace("__"," ",$service["name"]); ///Here you replacing "__" with " " in original service name!!!
          $carpcfr=str_replace("__"," ",$service["name"]);

```

**Comment by rbicelli** [comment]
Ok, now I understand. Thanks.
Corrected with latest commit.
