### ISSUE TITLE
Can't copy the php into root/scripts directory doesn't exisit

### ISSUE THREAD

**Issue by TidalWave123** [rbicelli/pfsense-zabbix-template#5]
I don't have a root/scripts directory on my pfsense box version 2.4.4 and I can't create one, I don't have permissions.

**Comment by rbicelli** [comment]
You have to ssh in your pfsense box as root.
If you can't create the directory under roou you could try to put script file in /usr/local/bin and modify the zabbix agent custom config according to it.
