### ISSUE TITLE
Cannot send request: wrong discovery rule type.

### ISSUE THREAD

**Issue by fabiograssofy** [rbicelli/pfsense-zabbix-template#50]
Ciao Riccardo!
first of all.. kudos and thanks for this great job!

I've tried to import your template on a brand new Zabbix 5.0.3 server.

Everything works fine but autodiscovery rules not. When I try to "Execute Now" I receive this error:

`Cannot send request: wrong discovery rule type.
`

If I change them to "Zabbix Agent" (so passive mode) they works fine. I've double checked and active check are enabled (all other items are working) and there is nothing that can explain why I'm receiving that error.

I've tried also on another setup based on Zabbix 4.4.10 but the error is the same.

I've solved by changing all the discovery rules to passive mode, but I'm trying to understand if there is someway to run them in active mode (I prefere due to better performance)

Thanks for your help!

**Comment by rbicelli** [comment]
Ciao!
Thanks for kudos :-)

I don't know why, but it seems you can't  manually trigger the discovery with template in active mode but wait for the process to run the discovery by itself.
When I was developing the template I had the same issue, and solved setting the discovery interval at very small values (30/60 secs).
Please try to create an active pfsense host and wait for the data.

**Comment by fabiograssofy** [comment]
Ciao!
You're right, I was not aware about this limitation in Zabbix and it seemed an issue of the autodiscovery rule.

I confirm that it works during the scheduled task

Thanks for the clarification!
