### ISSUE TITLE
radvd on carp slave

### ISSUE THREAD

**Issue by Phurion** [rbicelli/pfsense-zabbix-template#51]
The service Router Advertisement Daemon(radvd) on a carp ip slave for the RA interface should be stopped. This template flags the trigger.

{**removed**:pfsense.value[service_value,radvd,status].last()}=0 and ( ({**removed**:pfsense.value[service_value,radvd,run_on_carp_slave].last()}=1 and {**removed**:pfsense.value[carp_status].last()}=2) or ( {**removed**:pfsense.value[carp_status].last()}=1) or ({**removed**:pfsense.value[carp_status].last()}=0) )

Above is what the discovery rule created. On the Dashboard it shows as "Down (0), Yes (1), Backup (2)"

**Comment by rbicelli** [comment]
Added radvd in array of services stopped on CARP Secondary.
