### ISSUE TITLE
gateway allredy down

### ISSUE THREAD

**Issue by Tararashka** [rbicelli/pfsense-zabbix-template#56]
hi. I'm using your template without success. everything was great. I added a new PFsense and got the gataway down event. I found out that there is a difference in /root/scripts/pfsense_zbx.php. But the file version has not changed. Is this an error or were there changes?

**Comment by rbicelli** [comment]
Sorry, download the latest release. I made some changes but I forgot to update the version informations.
Will fix it in the next commit.
