### ISSUE TITLE
PFSENSE Cannot evaluate expression: 

### ISSUE THREAD

**Issue by randysrs** [rbicelli/pfsense-zabbix-template#57]
hey getting a error in zabbix stating unkown 
pfsense.value[system,new_version_available].last()}=1

Cannot evaluate expression: "Cannot evaluate function "SRS-FW1-COLORED:pfsense.value[system,new_version_available].last()": item is not supported.".

**Comment by rbicelli** [comment]
Did you correctly setup the agent? Sounds like you didn't configure server active parameter.
