### ISSUE TITLE
IPsec Multiply Servers Issue

### ISSUE THREAD

**Issue by dragoangel** [rbicelli/pfsense-zabbix-template#59]
Warning: array_key_exists() expects parameter 2 to be array, unknown given in /root/pfsense_zbx.php on line 810

```
if (array_key_exists($value, $valuemap))
          return $valuemap[$value];
```

Looks like valuemap is missing, in $value there is correctly displayed server IP.

**Comment by rbicelli** [comment]
In my testing machine I've only a single ipsec tunnel with a single phase 2.
Please launch the script without arguments and post the result of IPsec status section, redacting the sensitive informations.

**Comment by dragoangel** [comment]
Hi, not sure how to send this, there 1k lines only about IPsec
I tried to redact sensetive data but this going to total mess 😢

**Comment by dragoangel** [comment]
I will send you this at mail, hope it fine

**Comment by rbicelli** [comment]
Have you idea which value Zabbix is trying to fetch?

**Comment by dragoangel** [comment]
On new line after error it writes GW IP, but this all so not sure what it tries or not tries insert in valuemap.

**Comment by rbicelli** [comment]
Please try latest commit, I removed some checks that are not working due to handle mismatch in Ipsec Phase 2.

**Comment by dragoangel** [comment]
Now speaking same about 811 line, one note there was not mine, but remote ip*

**Comment by rbicelli** [comment]
Please try via pfsense cli:
`php pfsense_zbx.php ipsec_ph1 3 remote-gateway`
`php pfsense_zbx.php ipsec_ph1 2 remote-gateway`

Only way is to go in Zabbix Host, check item created by discovery, and call the correspondent php script one by one.

I committed another version of php script which checks for $valuemap variable. maybe you are using a different version of php.

FYI I think fixed your gateway problem, please check it out!

**Comment by dragoangel** [comment]
Thank you, I will check this tommorow and reply back.

pfsense which has multiple ipsec + multiple phases is on 2.5 developer branch. I will check what php version it use if it will help.

Issue with GW status is reproduce (on both stable and development pfsense), will try debug it tommorow.

**Comment by rbicelli** [comment]
I'm closing the issue since I did some improvements on IPsec side, most regarding 2.5.

**Comment by dragoangel** [comment]
Sorry, had another issues for long time with zabbix so had not working monitoring and forget about this issue
