### ISSUE TITLE
Add UnsafeUserParameters to how to

### ISSUE THREAD

**Issue by Flawioo** [rbicelli/pfsense-zabbix-template#60]
Hi, 
I had some problems to get some data about openvpn clients from pfsense box because the default zabbix agent conf didn't permit the use of special characters like my error log below:

<code>
69979:20210121:111322.537 active check "pfsense.value[openvpn_server_uservalue_numeric,"2+[error]",peer_id]" is not supported: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.
</code>

![image](https://user-images.githubusercontent.com/17605608/105364270-beae6e00-5bdb-11eb-8218-8ddba14d6059.png)

To correct this issue I just have added the parameter in the config file and the collections were done partially ok.

UnsafeUserParameters=1

![image](https://user-images.githubusercontent.com/17605608/105363907-5069ab80-5bdb-11eb-83dd-d06cd4c07819.png)

Some errors still persists because this box I've referred is a backup node from a pfsense carp cluster and just have a openvpn running on the master node. It is acceptable.

![image](https://user-images.githubusercontent.com/17605608/105366289-ed2d4880-5bdd-11eb-9e05-74474d931211.png)

No more errors were found in the log file as below:

![image](https://user-images.githubusercontent.com/17605608/105366608-4ac19500-5bde-11eb-8043-7fd696be6505.png)

**Comment by rbicelli** [comment]
Are you using the latest commit?
Please check Issue #58, I added a special char replacement for openvpn clients.

**Comment by Flawioo** [comment]
Yes, I'm using the last one.
I've also searched the issues about this but I think my word weren't the correct to this issue.
No problem, I just wanted to help someone with the same issue or you if you had hadn't saw before.

**Comment by rbicelli** [comment]
Sorry did read too fast your post!

Regarding unsafe parameters, you don't need to set UnsafeUserParameters=1. Latest version of PHP Script should do the special chars replacement transparently. You only have to update the php script and wait discovery to run. You will see new items appearing and old items becoming deprecated.

As for OpenVPN, in my CARP setup I tend to put OpenVPN listening on localhost, then NAT fromone or more CARP VIPs. In this case the service stays up on both nodes and you shouldn't have problems with missing values.
