### ISSUE TITLE
Ignore iperf service in services discovery

### ISSUE THREAD

**Issue by dani** [rbicelli/pfsense-zabbix-template#61]
The iperf service (not installed by default but provided in the iperf package) is not always running, but only started on demande when you want to use it.
As such, it's better to ignore it, and remove it from service discovery. Like https://git.fws.fr/fws/pfsense-zabbix/commit/89fb337ff0440eb4e6d5497a7020cf6d2c4da59f

**Comment by rbicelli** [comment]
I think is better to add a Filter in the Discovery Rule in Zabbix than hardcoding it in the php script.

Try this:
In Administration->General->Regular Expression add a new Regexp
name: **pfSense Services Names for Discovery"
value: Result is False ^(iperf)$

Then in Configuration->Templates->pfSense Active->Discovery List->Services Discovery->Filters add new Filter:

Macro {#SERVICE} matches @pfSense Services Names for Discovery

Then you'll have a flexible system for ignoring unwanted services from discovery.

For the reference check Service Discovery in Windows OS Template.

Will add the filter in next commit.

**Comment by dani** [comment]
You're right, it's cleaner to filter this on Zabbix side

**Comment by LinuxCuba** [comment]
> I think is better to add a Filter in the Discovery Rule in Zabbix than hardcoding it in the php script.
> 
> Try this:
> In Administration->General->Regular Expression add a new Regexp
> name: **pfSense Services Names for Discovery**
> value: Result is False ^(iperf)$
> 
> Then in Configuration->Templates->pfSense Active->Discovery List->Services Discovery->Filters add new Filter:
> 
> Macro {#SERVICE} matches **@pfsense Services Names for Discovery**
> 
> Then you'll have a flexible system for ignoring unwanted services from discovery.
> 
> For the reference check Service Discovery in Windows OS Template.
> 
> Will add the filter in next commit.

Hi @rbicelli I have followed all the steps, over and over again, and this does not work, I have a doubt, The macro matches is with @ in front, and something else in the name of the **pfSense** expression is with a capital S, and in the Macro filter **pfsense** with s lower case. I am use the last pfsense version 2.5.1 and Zabbix agent 5.0, The Zabbix server is 5.0.3.
Thansk for you help, great work.

**Comment by GuillaumeHullin** [comment]
Hi,
I don't know if @LinuxCuba is still looking for a solution to this but I can propose mine.

In Service Discovery Triggers **Service {#DESCRIPTION} is not running**
I modified the expression to:
```
{Template pfSense Active:pfsense.value[service_value,{#SERVICE},status].last()}=0 
and {$PFSENSE_SRVC_MONITORING:"{#SERVICE}"}=1 
and (
    ({Template pfSense Active:pfsense.value[service_value,{#SERVICE},run_on_carp_slave].last()}=1 
    and {Template pfSense Active:pfsense.value[carp_status].last()}=2)
    or ( {Template pfSense Active:pfsense.value[carp_status].last()}=1)
    or ({Template pfSense Active:pfsense.value[carp_status].last()}=0)
)
```

I added those macro in template (to enable monitoring by default and disable monitoring for few services)
```
{$PFSENSE_SRVC_MONITORING} = 1 (Enable monitoring of Services)
{$PFSENSE_SRVC_MONITORING:"dnsbl"} = 0 (Disable monitoring of Service pfBlockerNG DNSBL Web Server)
{$PFSENSE_SRVC_MONITORING:"iperf"} = 0 (Disable monitoring of Service iperf Network Performance Testing Daemon/Client)
{$PFSENSE_SRVC_MONITORING:"pcscd"} = 0 (Disable monitoring of PC/SC Smart Card Daemon due to https://redmine.pfsense.org/issues/12095)
```

The idea is that I monitor several pfSense so I can control which service I want to disable monitor in a flexible manner.

If I want to enable dnsbl monitoring on one host, then I just add the macro {$PFSENSE_SRVC_MONITORING:"dnsbl"} = 1

If I want to disable XXXX, then I just add the macro {$PFSENSE_SRVC_MONITORING:"dnsbl"} = 0
