### ISSUE TITLE
Gateway Issue

### ISSUE THREAD

**Issue by ShaunLoureiro** [rbicelli/pfsense-zabbix-template#65]
Hey man!
This template is awesome and have it installed on about 20 firewalls at work! 
Recently pfsense did an update to 2.5. Everything else has been working great but since updating a few firewalls to 2.5 all those gateways have stopped working. I get down(5) on the gateway but packet loss works.
I see you have done updates on the template last month and i am still using one of the older versions. 
Will updating the template and xml sort out this issue possible?

Thanks man. 
Appreciate any help :)

**Comment by rbicelli** [comment]
Hey! Glad to hear that!
First, try to update to the latest version of template and PHP script.
Then in the template disable item "DHCP Failover Pool Problems", which has to be fixed in order to work with 2.5.
See if your gateway problem remains.

**Comment by ShaunLoureiro** [comment]
Thanks, i updated the php script and removed the pre processing steps and it seems to have worked. Now to go through all the firewall and update! Thanks for the help bud
