### ISSUE TITLE
Zabbix Server 3.0 Support

### ISSUE THREAD

**Issue by mindesbunister** [rbicelli/pfsense-zabbix-template#66]
Hi,

do you think it is possible to add Zabbix 3.0 Support. When i try to import the template i get the following

![grafik](https://user-images.githubusercontent.com/32161838/109133019-cfab4b80-7754-11eb-8248-9298668791e6.png)

**Comment by rbicelli** [comment]
Sorry, I don't plan adding support to older version of Zabbix, please consider upgrading your Zabbix installation, if applicable, or try to convert the template by yourself.
