### ISSUE TITLE
Discovery: Value should be a JSON object.

### ISSUE THREAD

**Issue by JSuenram** [rbicelli/pfsense-zabbix-template#67]
Well, monitoring 6 pfSense with this template.
2 of them having Problems with discovery. 
Value should be a JSON object. Validator gives VALID (RFC 8259) for returned JSON.
Maybe a Zabbix issue with 4.0.29. Unsure for now. Difference between working and non working are installed FRR-Services which have forward slash in description. Maybe that's an issue?

Sample-JSON for Services with is returned when issue happens:
{
   "data":[
      {
         "{#SERVICE}":"zabbix_agentd",
         "{#DESCRIPTION}":"Zabbix Agent Host Monitor Daemon"
      },
      {
         "{#SERVICE}":"FRR__zebra",
         "{#DESCRIPTION}":"FRR core/abstraction daemon"
      },
      {
         "{#SERVICE}":"FRR__staticd",
         "{#DESCRIPTION}":"FRR static route daemon"
      },
      {
         "{#SERVICE}":"FRR__bfdd",
         "{#DESCRIPTION}":"FRR BFD daemon"
      },
      {
         "{#SERVICE}":"FRR__bgpd",
         "{#DESCRIPTION}":"FRR BGP routing daemon"
      },
      {
         "{#SERVICE}":"FRR__ospfd",
         "{#DESCRIPTION}":"FRR OSPF routing daemon"
      },
      {
         "{#SERVICE}":"FRR__ospf6d",
         "{#DESCRIPTION}":"FRR OSPF6 routing daemon"
      },
      {
         "{#SERVICE}":"unbound",
         "{#DESCRIPTION}":"DNS Resolver"
      },
      {
         "{#SERVICE}":"ntpd",
         "{#DESCRIPTION}":"NTP clock sync"
      },
      {
         "{#SERVICE}":"syslogd",
         "{#DESCRIPTION}":"System Logger Daemon"
      },
      {
         "{#SERVICE}":"dpinger",
         "{#DESCRIPTION}":"Gateway Monitoring Daemon"
      },
      {
         "{#SERVICE}":"bsnmpd",
         "{#DESCRIPTION}":"SNMP Service"
      },
      {
         "{#SERVICE}":"sshd",
         "{#DESCRIPTION}":"Secure Shell Daemon"
      }
   ]
}

**Comment by rbicelli** [comment]
It could be the forward slash, if you are familiare with php, edit the pfsense_zbx.php

Line 323: Change

`$json_string .= ',"{#DESCRIPTION}":"' . $service['description'] . '"';`

to

`$json_string .= ',"{#DESCRIPTION}":"' . str_replace("/","",$service['description']) . '"';`

And see if it helps. If your problems solves i will addd asanitization function for the json.

**Comment by JSuenram** [comment]
> It could be the forward slash, if you are familiare with php, edit the pfsense_zbx.php
> 
> Line 323: Change
> 
> `$json_string .= ',"{#DESCRIPTION}":"' . $service['description'] . '"';`
> 
> to
> 
> `$json_string .= ',"{#DESCRIPTION}":"' . str_replace("/","",$service['description']) . '"';`
> 
> And see if it helps. If your problems solves i will addd asanitization function for the json.

Hi,

I did the change on both pfSense nodes. Unfortunately it did not help.
I digged a bit deeper and it seems that most Discovery-Rules fail with "Value should be a JSON object"

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/68963439/109663281-36bd6b80-7b6c-11eb-87f9-5a4d5a67ab37.png">

Also values which are discovered/hardcoded show not suitable value.
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/68963439/109663503-78e6ad00-7b6c-11eb-804f-3057205b5695.png">

**Comment by rbicelli** [comment]
Did you configured Zabbix Agent in pfsense for active checks?
Which version of pfsense are you running?

**Comment by JSuenram** [comment]
Yes, sure Zabbix Agent active checks are enabled and configured. Some of the active checks are working.
pfsense Version is current pfsense+ 21.02-RELEASE-p1 (amd64). However we have also 2 other pas with same version, which are running perfectly with your template.
Zabbix Server is 4.029, agent is 4.027 on pfsense.

**Comment by rbicelli** [comment]
Please check if the script is running fine, try from pfsense console `php root/scripts/pfsense_zbx.php`

**Comment by JSuenram** [comment]
Script is running fine, result attached... 
[result.zip](https://github.com/rbicelli/pfsense-zabbix-template/files/6074584/result.zip)
