### ISSUE TITLE
IPSEC status irregularities

### ISSUE THREAD

**Issue by danjeman** [rbicelli/pfsense-zabbix-template#68]
Firstly loving the template..

Having some odd issues though with the IPSEC tunnel status being reported as down when it's up but only on some tunnels.. trying to work through the code and xml to see what could be causing it. This appears to only be happening on 21.02, 2.5 seems ok.. Zabbix 5.0.9 and zabbix agent5 on pfsense
On 1 SG-2100 (single unit so CARP set to 0) with only a single tunnel it is returning an error for `status` - `Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "-9"` (actually just spotted an SG-2100 on 2.4.5p1 is also doing the same) and then on an SG-7100 (CARP enabled pair) 5 of 12 tunnels are reported down (on the active unit) when only 2 are actually down. XML seems to show `[state] => ESTABLISHED` correctly for all but `php pfsense_zbx.php ipsec_ph1 8 status` for instance returns 0 when it is showing ESTABLISHED..

I appear to have a minor bug too in that if phase 1 is IKEv2 then it is still trying to report the tunnel mode, which doesn't exist for v2

Will do some proper investigation and report with details but wanted to flag this in case you're already aware and it's a simple config issue my end...

Thanks

**Comment by danjeman** [comment]
So...  On the stand alone unit looks like the issue is with carp status (or rather a lack of carp) - line 607 ` $value = $value + (10 * ($carp_status-1));` hence `Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "-9"`
this quick patch, I think, should fix that -   https://github.com/danjeman/pfsense-zabbix-template/commit/57324cf3a396adc24f64af198fdc223442c0ff8f It is working on a couple of my devices...

The ph1 tunnel mode bug only appears to happen if the `key exchange version` is configured as v2 - if it's configured as auto then it reports it as `Main (0)` but also reports the type as `Auto (0)` - I think we should report the type status rather than the configured value? Will have a think and look into this.

Still working through the odd some tunnels reported down when they are up...

**Comment by JSuenram** [comment]
Any update on this?
We are also having same issues ob some boxes...

**Comment by rbicelli** [comment]
I can't reproduce the issue on my boxes. I only have 2-3 tunnels between pfSenses and Fortigates.
Don't have access to pfsense 21.02
Please post the output of the pfsense_zbx.php so I can examine it.

**Comment by JSuenram** [comment]
Maybe I am getting this wrong, but it looks like IPSEC-Connection-State is not returning as value?
-------------------
IPsec:
IPsec Status:
Array
(
    [0] => Array
        (
            [con-id] => con100000
            [uniqueid] => 36
            [version] => 2
            [state] => ESTABLISHED
            [local-host] => xxx.xxx.xxx.xxx
            [local-port] => 4500
            [local-id] => xxx.xxx.xxx.xxx
            [remote-host] => yyy.yyy.yyy.yyy
            [remote-port] => 4500
            [remote-id] => PFS.domain.local
            [initiator-spi] => c176fa0d61df622f
            [responder-spi] => 369161cee2511d57
            [nat-remote] => yes
            [nat-any] => yes
            [encr-alg] => AES_GCM_16
            [encr-keysize] => 128
            [prf-alg] => PRF_HMAC_SHA2_256
            [dh-group] => MODP_2048
            [established] => 19467
            [rekey-time] => 6343
            [child-sas] => Array
                (
                    [con100000-257] => Array
                        (
                            [name] => con100000
                            [uniqueid] => 257
                            [reqid] => 1
                            [state] => INSTALLED
                            [mode] => TUNNEL
                            [protocol] => ESP
                            [encap] => yes
                            [spi-in] => c1ead921
                            [spi-out] => c8e33070
                            [encr-alg] => AES_GCM_16
                            [encr-keysize] => 128
                            [dh-group] => MODP_2048
                            [bytes-in] => 2016
                            [packets-in] => 24
                            [use-in] => 50
                            [bytes-out] => 3360
                            [packets-out] => 24
                            [use-out] => 50
                            [rekey-time] => 2142
                            [life-time] => 2827
                            [install-time] => 773
                            [local-ts] => Array
                                (
                                    [0] => 10.255.34.0/24|/0
                                )

                            [remote-ts] => Array
                                (
                                    [0] => 172.20.16.0/20|/0
                                )

                        )

                )

        )

)

**Comment by Kratosvoid** [comment]
hello, first thanks a lot for the template, I'm having the same problem is there any update?

**Comment by YiSuchong** [comment]
Morning, same update about the problem?

**Comment by Flawioo** [comment]
Hi all!

The problem I'm having here sounds like some of yours guys.
The item always return 0 (Down) even if the tunnel was successfully established.

![image](https://user-images.githubusercontent.com/17605608/119036188-daa5fe80-b986-11eb-90aa-c80c260cb0fa.png)

**Comment by rbicelli** [comment]
What's saying the array key [state] => of ipsec status calling the script without arguments?
I'm suspecting a bug in value mapping function of php script.

**Comment by maxoulamenasse** [comment]
Hello,

In my case [state] is `ESTABLISHED`

```json
IPsec: 
IPsec Status: 
Array
(
    [0] => Array
        (
            [con-id] => con200000
            [uniqueid] => 20
            [version] => 2
            [state] => ESTABLISHED
            [local-host] => XXX.XXX.XXX.XXX
            [local-port] => 4500
            [local-id] => XXX.XXX.XXX.XXX
            [remote-host] =>XXX.XXX.XXX.XXX
            [remote-port] => 4500
            [remote-id] => XXX.XXX.XXX.XXX
            [initiator] => yes
            [initiator-spi] => 1947036e3d7b81cd
            [responder-spi] => deb6604daf3fe67c
            [nat-remote] => yes
            [nat-any] => yes
            [encr-alg] => AES_CBC
            [encr-keysize] => 256
            [integ-alg] => HMAC_SHA2_256_128
            [prf-alg] => PRF_HMAC_SHA2_256
            [dh-group] => MODP_2048_256
            [established] => 310
            [rekey-time] => 24387
            [child-sas] => Array
                (
                    [con200000-103] => Array
                        (
                            [name] => con200000
                            [uniqueid] => 103
                            [reqid] => 1
                            [state] => INSTALLED
                            [mode] => TUNNEL
                            [protocol] => ESP
                            [encap] => yes
                            [spi-in] => ca453c48
                            [spi-out] => c999675e
                            [encr-alg] => AES_CBC
                            [encr-keysize] => 256
                            [integ-alg] => HMAC_SHA2_256_128
                            [dh-group] => MODP_2048_256
                            [bytes-in] => 0
                            [packets-in] => 0
                            [use-in] => 549
                            [bytes-out] => 0
                            [packets-out] => 0
                            [rekey-time] => 334
                            [life-time] => 999
                            [install-time] => 2601
                            [local-ts] => Array
                                (
                                    [0] => 192.168.112.128/25|/0
                                )

                            [remote-ts] => Array
                                (
                                    [0] => 10.249.124.0/23|/0
                                )

                        )

                )

        )

    [1] => Array
        (
            [con-id] => con100000
            [uniqueid] => 17
            [version] => 2
            [state] => ESTABLISHED
            [local-host] => XXX.XXX.XXX.XXX
            [local-port] => 4500
            [local-id] => XXX.XXX.XXX.XXX
            [remote-host] => XXX.XXX.XXX.XXX
            [remote-port] => 4500
            [remote-id] => XXX.XXX.XXX.XXX
            [initiator] => yes
            [initiator-spi] => bf9451383623f5c5
            [responder-spi] => be7bdc353ba87c60
            [nat-remote] => yes
            [nat-any] => yes
            [encr-alg] => AES_CBC
            [encr-keysize] => 256
            [integ-alg] => HMAC_SHA2_256_128
            [prf-alg] => PRF_HMAC_SHA2_256
            [dh-group] => MODP_2048_256
            [established] => 20038
            [rekey-time] => 3537
            [child-sas] => Array
                (
                    [con100000-105] => Array
                        (
                            [name] => con100000
                            [uniqueid] => 105
                            [reqid] => 1
                            [state] => INSTALLED
                            [mode] => TUNNEL
                            [protocol] => ESP
                            [encap] => yes
                            [spi-in] => c951bffc
                            [spi-out] => c6a028ab
                            [encr-alg] => AES_CBC
                            [encr-keysize] => 256
                            [integ-alg] => HMAC_SHA2_256_128
                            [dh-group] => MODP_2048_256
                            [bytes-in] => 0
                            [packets-in] => 0
                            [use-in] => 550
                            [bytes-out] => 0
                            [packets-out] => 0
                            [rekey-time] => 2436
                            [life-time] => 3051
                            [install-time] => 549
                            [local-ts] => Array
                                (
                                    [0] => 192.168.112.128/25|/0
                                )

                            [remote-ts] => Array
                                (
                                    [0] => 10.249.124.0/23|/0
                                )

                        )

                )

        )

)

```

When I execute the script manually there are the outputs :
```
/usr/local/bin/php /root/scripts/pfsense_zbx.php ipsec_ph1 0  status
0
``` 
```
/usr/local/bin/php /root/scripts/pfsense_zbx.php ipsec_ph1 1  status
0
```

**Comment by cat1510** [comment]
Hi together,

we have the same issue in general but found out something different.
If we use IPSec with VTI the State is shown correctly.
Also we recognized that connection name and reqid is different.
Let me show you 2 different examples:

**IPSEC VTI Tunnel working: ipsec statusall**

Security Associations (3 up, 0 connecting):
     con1000[243]: ESTABLISHED 4 hours ago, XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     con1000[243]: IKEv2 SPIs: XXXXXXXXXXXXXXXXXXXXX, rekeying in 2 hours
     con1000[243]: IKE proposal: AES_GCM_16_128/PRF_AES128_XCBC/MODP_2048
     con1000{1574}:  INSTALLED, TUNNEL, reqid 1000, ESP SPIs: XXXXXXXXXXXXXXXXXXXXX
     con1000{1574}:  AES_GCM_16_128/MODP_2048, 564148 bytes_i, 725752 bytes_o, rekeying in 50 minutes
     con1000{1574}:   0.0.0.0/0|/0 === 0.0.0.0/0|/0


**IPSEC Tunnel status NOT working: ipsec statusall**

Security Associations (1 up, 0 connecting):
   con100000[3]: ESTABLISHED 5 hours ago, XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   con100000[3]: IKEv2 SPIs: XXXXXXXXXXXXXXXXXXXXXXXXXXXX, rekeying in 80 minutes
   con100000[3]: IKE proposal: AES_GCM_16_128/PRF_AES128_XCBC/MODP_2048
   con100000{25}:  INSTALLED, TUNNEL, reqid 1, ESP SPIs: XXXXXXXXXXXXXXXXXXXX
   con100000{25}:  AES_GCM_16_128/MODP_2048, 72796 bytes_i (531 pkts, 2s ago), 109888 bytes_o (589 pkts, 2s ago), rekeying in 43 minutes
   con100000{25}:   192.168.X.X/24|/0 === 192.168.X.X/24|/0


With this in mind we checked the PHP script.
We believe the issue resides in the function: function pfz_ipsec_status($ikeid,$reqid=-1,$valuekey='state'){ in Line 550.
But this is just a guess and our skills in PHP are not even basic.
If you cloud have a look or give me an advice 'how to debug' I would do for further information of course.

We will test another IPSec VTI Tunnel today, just to see if this is the difference.

thanks a lot for the great work,

CAT

**Comment by Corgumolax** [comment]
Hi, I had some kind the same problem where ipsec phase 1 status was always returning 0.  We have Carp enable on our fw. And the line 609: `$value = $value + (10 * ($carp_status-1));` seems to be the cause. I changed it with  `$value = pfz_valuemap('ipsec.state', strtolower($tmp_value)) + (10 * ($carp_status-1)) ;` and the function returns the value expected according to "real" tunnel status.

**Comment by rbicelli** [comment]
I fixed changing the value mapper function. Thanks!
