### ISSUE TITLE
Field "name" cannot be set to NULL. on template import

### ISSUE THREAD

**Issue by ydessert** [rbicelli/pfsense-zabbix-template#73]
Hi,

We are facing an error on zabbix during the template import with the Field "name" cannot be set to NULL.

Zabbix 4.0.31

Cannot find why we have this kind of error. The xml seems clean...
Anyone have a clue where to search ?

Thanks

**Comment by rbicelli** [comment]
Please try to empty the <description> field on top of templates.
In the past it caused issues with Zabbix 4.0

**Comment by ydessert** [comment]
Can you tell me wich field to empty please ?

**Comment by rbicelli** [comment]
sorry, the **description** fields

**Comment by ydessert** [comment]
I've removed the description living the xml as this : 
`<template>Template pfSense Active</template>
            <name>pfsense Active</name>
            <description></description>`
but the error is still the same.
I've verified if no strange caracters are in the name field, but everything ok in the file.
Very strange...
