### ISSUE TITLE
Ipsec Phase 1 always down (+ fix)

### ISSUE THREAD

**Issue by trooster** [rbicelli/pfsense-zabbix-template#76]
My ipsec phase 1 was always marked as down. Changing line 571 and 576 to substract 4 zero's instead of two solved my issue.

https://github.com/rbicelli/pfsense-zabbix-template/blob/d18056cf8af33e6993312d8bb86622bc505845c3/pfsense_zbx.php#L571

https://github.com/rbicelli/pfsense-zabbix-template/blob/d18056cf8af33e6993312d8bb86622bc505845c3/pfsense_zbx.php#L576

**Comment by rbicelli** [comment]
Tried on my system and it reports tunnels down. Must better identify your case so could write a fix that doesn't break the rest.

**Comment by trooster** [comment]
I've done nothing special. Using PfSense 2.5.1. Created the IPsec tunnels using the gui. The IpSec ID's are con100000, con200000 etc.

**Comment by rbicelli** [comment]
looks like in earlier versions (I'm still running 2..4 on instance with ipsec tunnels) IPsec connection are enumerated con1000, con2000.
Added a conditional, please try latest commit and see if it works for you.

**Comment by danjeman** [comment]
FYI I still have an issue on some of my tunnels but spotted my con ID's vary, this is on 21.05 all are tunnel based no VTI
con1000 reports correctly as tunnel 1
con2000 reports correctly as tunnel 2
con5000 reports correctly as tunnel 5
con9000 reports correctly as tunnel 9
con11000 reports correctly as tunnel 11
con12000 reports correctly as tunnel 12
con700000 reports incorrectly as tunnel 7 (which is what is listed) but if I run it manually against tunnel 700 then reports correctly
con800000 reports incorrectly as tunnel 8 (as per listed zabbix entry) manually run as 800 reports ok
con1400000 reports incorrectly as tunnel 14 but manually ok as tunnel 1400...

will look at a fix

**Comment by rbicelli** [comment]
Looks like for properly detect the connection id I need to:
- substract "con" from the connection id
- divide the number obtained by 1000

This could work.

**Comment by rbicelli** [comment]
Committed the fix. Please check it out.
Please report compatibility with 21.05 so I can update the docs.

**Comment by danjeman** [comment]
Unfortunately dividing by 1000 still sees con_ids of 700 instead of 7 and 1400 instead of 14 etc whereas trying removing 5 0s first and then 3 if that results in error etc catches both id types... could try dividing by 100000 1st and then 1000... but would then need to test it was whole number too

**Comment by danjeman** [comment]
Subtracting con and dividing by 1000 could work if the same was done for listing the configured tunnel id? Just means you'd end up with non sequential tunnel ids

**Comment by rbicelli** [comment]
Could you please send me privately the output  of the ipsec sections of the script output called with no arguments?

**Comment by danjeman** [comment]
emailed it over. Thanks

**Comment by rbicelli** [comment]
A solution could be:
after dividing per 1000, if result is greater than 100, divide per 100...
OR...
find similarities between configured phase and connection (ip address, mode ...)
Adding this could be more robust

**Comment by danjeman** [comment]
I suspect the second option will ultimately be the best solution. However latest commit with the 1st option works for me...

**Comment by trooster** [comment]
Unfortunately, the latest commit is not working for me. I will do some debugging later and share my thoughts.

**Comment by rbicelli** [comment]
Hi @trooster, could you please send me privately a copy of ipsec sections of the output of the script called without arguments?
Please redact the sensitive informations, such private keys but leave the ip address or find/replace them in order to find correspondence between configuration and status.
Thanks

**Comment by ananiasfilho** [comment]
I have same issue as @trooster

**Comment by rbicelli** [comment]
@ananiasfilho please send me inprivate my the relevant section of the output of php script called without arguments.

**Comment by rbicelli** [comment]
@ananiasfilho please try the pfsense_zbx script of the development branch and tell me if it solves your problem.

**Comment by ananiasfilho** [comment]
@rbicelli Yes! Its working as expect now. Thank you!

**Comment by trooster** [comment]
@rbicelli Yes, everything works as expected!
