### ISSUE TITLE
Import error - zabbix server 5.4

### ISSUE THREAD

**Issue by vinhthai1989** [rbicelli/pfsense-zabbix-template#80]
Cannot import  template_pfsense_active

Cannot read XML: (41) Specification mandates value for attribute data-pjax-transient [Line: 88 | Column: 90]

please helpme

**Comment by rbicelli** [comment]
Templeates are exported from Zabbix 4.0.
I migrated my systems to Zabbix 5.0 LTS so re-exported from it.
Please check de develop branch.

**Comment by vinhthai1989** [comment]
> Templeates are exported from Zabbix 4.0.
> I migrated my systems to Zabbix 5.0 LTS so re-exported from it.
> Please check the develop branch.

Yes, after importing the template successfully, i get the following error from zabbix agent log:

 21017:20210713:020233.885 using configuration file: /usr/local/etc/zabbix52/zabbix_agentd.conf
 21017:20210713:020233.885 agent #0 started [main process]
 21154:20210713:020233.886 agent #1 started [collector]
 21200:20210713:020233.887 agent #2 started [listener #1]
 21484:20210713:020233.888 agent #3 started [listener #2]
 21513:20210713:020233.893 agent #4 started [listener #3]
 21804:20210713:020233.894 agent #5 started [active checks #1]
 21484:20210713:022907.182 failed to accept an incoming connection: from X.X.X.X: TLS connections are not allowed
 21017:20210713:023534.616 Got signal [signal:15(SIGTERM),sender_pid:22806,sender_uid:0,reason:65537]. Exiting ...
 21017:20210713:023534.619 Zabbix Agent stopped. Zabbix 5.2.6 (revision 798506596c).
 24269:20210713:023539.667 Starting Zabbix Agent [PFSENSE]. Zabbix 5.2.6 (revision 798506596c).
 24269:20210713:023539.667 **** Enabled features ****
 24269:20210713:023539.667 IPv6 support:          YES
 24269:20210713:023539.667 TLS support:           YES
 24269:20210713:023539.667 **************************
 24269:20210713:023539.667 using configuration file: /usr/local/etc/zabbix52/zabbix_agentd.conf
 24269:20210713:023539.668 agent #0 started [main process]
 24305:20210713:023539.668 agent #1 started [collector]
 24434:20210713:023539.670 agent #2 started [listener #1]
 24512:20210713:023539.671 agent #3 started [listener #2]
 24704:20210713:023539.677 agent #4 started [listener #3]
 24834:20210713:023539.677 agent #5 started [active checks #1]
 24834:20210713:023539.689 active check configuration update from X.X.X.X:10051] started to fail (TCP successful, cannot establish TLS to [[X.X.X.X:10051]: SSL_connect() set result code to SSL_ERROR_SSL: file /build/ce-crossbuild-252/sources/FreeBSD-src/crypto/openssl/ssl/record/rec_layer_s3.c line 1544: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure: SSL alert number 40: TLS read fatal alert "handshake failure")
 24834:20210713:023639.892 active check configuration update from X.X.X.X:10051] is working again
[2.5.2-RELEASE][admin@PFSENSE.vfs.com.vn]/var/log/zabbix-agent:

Plsease helpme, Bro

**Comment by rbicelli** [comment]
Looks like Zabbix agent has problems connecting to zabbix server. Check if zabbix server is reachable and also check if agent is configured for active checks.

**Comment by vinhthai1989** [comment]
![image](https://user-images.githubusercontent.com/87307317/125556615-a7158de5-c7cc-47af-bc36-66f3e5ac1b45.png)
![image](https://user-images.githubusercontent.com/87307317/125556805-5b47f758-7c99-4a08-9793-07a8c922441b.png)
![image](https://user-images.githubusercontent.com/87307317/125556875-1b87a949-b823-46df-b4f6-e0e895653c7a.png)
![image](https://user-images.githubusercontent.com/87307317/125556919-6f606792-83c9-4c66-a45f-ee393e39b6f9.png)
![image](https://user-images.githubusercontent.com/87307317/125557575-7654133a-88bf-4d92-ba83-32ac98fc5bf9.png)
![image](https://user-images.githubusercontent.com/87307317/125557667-767de190-8a68-408e-9ea2-896044735acc.png)
![image](https://user-images.githubusercontent.com/87307317/125557712-1f501b61-e318-4416-b9c7-613b7d1cf382.png)
![image](https://user-images.githubusercontent.com/87307317/125557971-3c1ece30-ba0b-4d95-9242-227ab9b90325.png)

**Comment by vinhthai1989** [comment]
If i replace template FreeBSD it is worked but template pfsense active not working

**Comment by maxoulamenasse** [comment]
In my case, i have installed zabbix_agent 5.2 for my pfsense but i have zabbix server 5.2 and it works like a charm

**Comment by alexandreuriel** [comment]
Não está realizando a coleta dos dados (Zabbix 5.0)
Poderia me dar um help?
![image](https://user-images.githubusercontent.com/38509026/142883850-372a673f-76a1-4e93-a3da-f8653505877c.png)
