### ISSUE TITLE
Invalid tag "/zabbix_export/version": version number not supported.

### ISSUE THREAD

**Issue by bsanra** [rbicelli/pfsense-zabbix-template#83]
Boa tarde, ao tentar importar templates no meu zabbix 4.4.7 ele me da essa mensagem:

Invalid tag "/zabbix_export/version": version number not supported.

![Capturar](https://user-images.githubusercontent.com/61694071/125983846-02ed0bbc-02aa-4320-a2ae-5b923f113c0d.PNG)

**Comment by rbicelli** [comment]
Hello, need to dig through commits and extract a template export compatibile with zabbix 4. Please be patient

**Comment by rbicelli** [comment]
Extracted old files from previous commits and added a Zabbix4 directory.
