### ISSUE TITLE
IPSec tunnels traffic

### ISSUE THREAD

**Issue by ananiasfilho** [rbicelli/pfsense-zabbix-template#84]
Any change to get this template to monitoring IPSec traffic on each tunnels?
I found a template on github if works as reference -> https://github.com/alanwds/zabbix_ipsec_pfsense
I just not need add more templates to my zabbix and would like to get all in one if possible.
If need tests and help i can be available to work with you on it.

**Comment by rbicelli** [comment]
I checked the link you provided and I have to say that doesn't integrate well with my template.
Anyway there are some other ways to monitor IPsec tunnel traffic:

1. in phase 2 status there's bytes in/bytes out, packets in/packets out that could be used to monitor tunnel traffic
2. you could always define an interface in pfsense assigned to tunnel  and see the statistics from here

**Comment by ananiasfilho** [comment]
@rbicelli Solved! 
As pfsense define it as encX - in our case, enc0 i can monitor IPSec traffic.
Please close this topic.
