### ISSUE TITLE
Does it work on zabbix 5.4.4?

### ISSUE THREAD

**Issue by thierrybla** [rbicelli/pfsense-zabbix-template#86]
I have tried every agent, many different settings but the Zabbix agent just doesn't seem to become green with this template.
![image](https://user-images.githubusercontent.com/28044044/133426856-c98f41e5-3e72-4d81-867c-d659e9f6e89b.png)
![image](https://user-images.githubusercontent.com/28044044/133427138-72240f2d-7090-413f-ae21-e9d65f505f01.png)
![image](https://user-images.githubusercontent.com/28044044/133426897-ee5ab027-64ad-4a9b-a979-e85f39e9a22b.png)
![image](https://user-images.githubusercontent.com/28044044/133426935-5839be04-9538-4da6-b7fb-3cd7c7fd2b76.png)
![image](https://user-images.githubusercontent.com/28044044/133426953-7cf72454-5fae-4a18-abc8-02e2f8f072f9.png)

Any ideas? Thanks in advance.

**Comment by GuillaumeHullin** [comment]
Do you see errors in Zabbix "Latest Data" if you check "Show details"?

**Comment by fbirlik** [comment]
I believe I'm also affected with my both pfsense instances.  Still, latest data and all graphs are populated, no visible errors reported.  Honestly I don't know what side effect this gray box causes.

![Screen Shot 2021-09-15 at 10 33 33 AM](https://user-images.githubusercontent.com/31392854/133464370-60a3036b-da7d-4f26-b7cc-da5718e0d8c6.png)

**Comment by thierrybla** [comment]
For me no data is coming in at all @fbirlik how did you manage to get any data?

**Comment by GuillaumeHullin** [comment]
@fbirlik Concerning the green label do not worry, this is totally normal. This is because none of the items are Zabbix **passive** agent . I think you only get the green ZBX when there are passive (when the server/proxy is the one requesting the data).
Here is an article that shows the difference. https://blog.zabbix.com/zabbix-agent-active-vs-passive/9207/
IMO, I prefer to have as much Active Agent as possible.

@thierrybla go to your pfsense host configuration (in zabbix interface). Go to the **Items** and see if there are errors marked on the right of the items.

**Comment by GuillaumeHullin** [comment]
Note: zabbix_server (Zabbix) 5.0.15

**Comment by thierrybla** [comment]
![image](https://user-images.githubusercontent.com/28044044/133479782-4f62323d-4ed1-4a35-9372-9d82d71a34cb.png)
This is what I see.

**Comment by GuillaumeHullin** [comment]
Ok and when you go in the main menu "Latest Data" and that you select your pfSense, what do you get?

**Comment by thierrybla** [comment]
![image](https://user-images.githubusercontent.com/28044044/133480306-546c9eb4-b978-4019-8718-93e43fee7f9a.png)
This, thanks for you help so far by the way :).

**Comment by GuillaumeHullin** [comment]
Ok so I see that there is 1 data... it's a start. Go to your pfSense, go to the Zabbix agent settings and then you press save. This will restart Zabbix Agent and also refresh the template data in the zabbix agent (meaning that your agent ask the server what data he should send).
You're welcome.

**Comment by thierrybla** [comment]
I am currently using Zabbix 5.4.4 and the 4.0 agent, should I change back to the 5.4 agent?

**Comment by GuillaumeHullin** [comment]
You mean you have 2 agents on your pfSense? If yes, remove the 4.0. You should only have zabbix-agent54 (from the Package Manager list)

**Comment by thierrybla** [comment]
I have changed agent, saved one more time but still not other data is coming in.

**Comment by GuillaumeHullin** [comment]
I just realized, in the config in pfSense Zabbix Agent... whats the value of Server Active?

**Comment by thierrybla** [comment]
As seen above I send a screenshot of my whole config.

**Comment by GuillaumeHullin** [comment]
ok then put your server IP address in Server Active.

**Comment by GuillaumeHullin** [comment]
https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_agentd
check ServerActive to readmore :)

**Comment by thierrybla** [comment]
Omg yes that fixed it, thanks @GuillaumeHullin I thought that the first server IP should have been enough..
