### ISSUE TITLE
SMART monitoring

### ISSUE THREAD

**Issue by dragoangel** [rbicelli/pfsense-zabbix-template#87]
As pfsense has build-in SMART monitoring, it would be cool to have this data in zabbix and triggers based on this data if something prefail or fail :)

**Comment by rbicelli** [comment]
Yes, but I'd make an overall check.
Something like a "SMART Status" item and a "SMART Alert" trigger.
Would it be ok?

**Comment by rbicelli** [comment]
Yes, like I did for DHCP status

**Comment by rbicelli** [comment]
Hello, just added SMART monitoring code. Need some time to test and will release it.

**Comment by dragoangel** [comment]
Nice, thanks you a lot

**Comment by dragoangel** [comment]
Thank you a lot, will check :)

**Comment by dragoangel** [comment]
Shows OK, thanks
