### ISSUE TITLE
unknown ip

### ISSUE THREAD

**Issue by AugustoRubio** [rbicelli/pfsense-zabbix-template#90]
Hi, can you help me?

I have this problem, my zabbix is not interpreting correctly if the agent is active or not. I noticed that this only happens when I activate the pfsense Active template. Other Linux-oriented templates the agent works correctly. I tested both the templates for zabbix 4 and 5. [error](https://drive.google.com/file/d/1750rtF0AIRKWaDJIgArlw8_SncJyBhNr/view)

I also couldn't run the speedtest part. [error python](https://drive.google.com/file/d/1LFI_tUtuYvn59wBCyeoHGK6kR3c9haDc/view?usp=sharing)

Zabbix 5.4.7
Grafana v8.2.3 (fb85ed6912)
Pfsense 2.5.2

**Comment by GuillaumeHullin** [comment]
Concerning the speediest part you could try what I work in the README of my fork https://github.com/Futur-Tech/futur-tech-zabbix-pfsense

Can you explain a bit more what you mean by "not interpreting".... do you get data?

**Comment by AugustoRubio** [comment]
Yes, I can get most of the data through grafana and zabbix. But zabbix does not understand that the server is on. Some network failures are detected, but when the server is shut down or restarted it cannot interpret. I'll try to run your fork's procedures.

**Comment by GuillaumeHullin** [comment]
> But zabbix does not understand that the server is on.

Are you referring to ZBX logo which is grey on the right of your screenshot?

**Comment by AugustoRubio** [comment]
[https://drive.google.com/file/d/19i7t4D4eBcFc32hAQJribxybNpk5MhnH/view?usp=sharing](https://drive.google.com/file/d/19i7t4D4eBcFc32hAQJribxybNpk5MhnH/view?usp=sharing)
That's right. But I realize that the server can detect some things and not others. Everything about networks he can see, but if the server is off he can't. Remembering that this ZABBIX server is outside my main network.

**Comment by GuillaumeHullin** [comment]
Ok tracking. The ZBX symbol will only become green when there are passive check. If every items are active then it will not turn green but stay grey... which is find. If it's red then it means that there are passive checks which doesn't reach your agent.

I understand that pfSense is not in your network... which is fine but I would maybe advise you to use pfSense as proxy for the network controlled by your pfSense. The pfSense agent then will just report to localhost (the pfSense proxy). In addition to reduce traffic between your networks it will also make more sense in your host... cause if the Zabbix proxy goes down because your WAN is down then your host in that network will keep reporting to the Zabbix proxy and you will not loose data.

**Comment by rbicelli** [comment]
> I also couldn't run the speedtest part. [error python](https://drive.google.com/file/d/1LFI_tUtuYvn59wBCyeoHGK6kR3c9haDc/view?usp=sharing)

Hello, regarding the python error (which isn't a python error) it is because your pfsense version isn't using python 3.7 (from 2.5.2 python version is 2.8), so your curl install cmd is:

```
curl -Lo /usr/local/lib/python3.8/site-packages/speedtest.py https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py

```
and it should be fine.

**Comment by AugustoRubio** [comment]
> Ok tracking. The ZBX symbol will only become green when there are passive check. If every items are active then it will not turn green but stay grey... which is find. If it's red then it means that there are passive checks which doesn't reach your agent.
> 
> I understand that pfSense is not in your network... which is fine but I would maybe advise you to use pfSense as proxy for the network controlled by your pfSense. The pfSense agent then will just report to localhost (the pfSense proxy). In addition to reduce traffic between your networks it will also make more sense in your host... cause if the Zabbix proxy goes down because your WAN is down then your host in that network will keep reporting to the Zabbix proxy and you will not loose data.

I liked your idea, I will try to follow the steps given in your README.

**Comment by GuillaumeHullin** [comment]
> Template Futur-Tech Module Zabbix agent active error. I tried to install the template from your repository but it's giving this error. I uploaded the other files from your fork but when I try to upload the template_pfsense_active file it gives me this error.

Which error? If you have a screenshot would be super.

**Comment by AugustoRubio** [comment]
> > Template Futur-Tech Module Zabbix agent active error. I tried to install the template from your repository but it's giving this error. I uploaded the other files from your fork but when I try to upload the template_pfsense_active file it gives me this error.
> 
> Which error? If you have a screenshot would be super.

[https://drive.google.com/file/d/1X7GZW75EvymF5FonRjacIh65Txh7c9Ry/view?usp=sharing](https://drive.google.com/file/d/1X7GZW75EvymF5FonRjacIh65Txh7c9Ry/view?usp=sharing)

**Comment by AugustoRubio** [comment]
@rbicelli Funny thing is that I just put the default configuration of the Linux template by Zabbix agent active and everything starts to work... [https://drive.google.com/file/d/12xYHffo-Pypa0wcoNiAkHWIizCOYuH59/view?usp=sharing](https://drive.google.com/file/d/12xYHffo-Pypa0wcoNiAkHWIizCOYuH59/view?usp=sharing) Do you still think there is a problem between pfsense and my zabbix server using your template?

@GuillaumeHullin He just tried to help me and I'm reporting the error that I knew about his fork, that's all.

**Comment by rbicelli** [comment]
@AugustoRubio It's difficult providing help without knowing articular details of your setup. If you want your probem solved we need at least:
- screenshot of configuration of Zabbix Agent in pfsense
- screenshot of configuration of pfSense host in Zabbix template
- logs on zabbix_agentd.log on pfsense

**Comment by GuillaumeHullin** [comment]
> @GuillaumeHullin I appreciate your contribution but I also think something weird is happening here. Sorry if I may seem rude, but @AugustoRubio is clearly lacking Zabbix knowledge and hijacking him to your fork is the first step for the recipe for confusion.

@rbicelli Yeah I understand you... I just wanted to help and my intention was not to hijack on my fork (I just thought it was better to link than copy paste what I wrote already).

I'll learn ASAP on how to make pull request properly and maybe propose you what I did add/change in my fork... I guess that's the way it should be.
