### ISSUE TITLE
Failed import

### ISSUE THREAD

**Issue by AugustoRubio** [rbicelli/pfsense-zabbix-template#92]
[https://drive.google.com/file/d/1X7GZW75EvymF5FonRjacIh65Txh7c9Ry/view](https://drive.google.com/file/d/1X7GZW75EvymF5FonRjacIh65Txh7c9Ry/view)
Hi, you were helping me on the other fork. I decided to close everything there as apparently the owner doesn't like to solve problems.

**Comment by GuillaumeHullin** [comment]
@AugustoRubio That's not true. He is right that I should not link my fork in his work... I can see that it is rude from me. Also, his work on this project and his answers on Issues (including my issues) are what make this repo going forward so please do not bash because you don't like the answers.
