### ISSUE TITLE
Gateway monitoring

### ISSUE THREAD

**Issue by carlo5henrique** [rbicelli/pfsense-zabbix-template#94]
Hello, 
I am having trouble monitoring the gateways. The template discovers the existing gateways but does not capture the data to generate the graphs.
Can you help me with some important tips for this operation?

Comments:
I am using pfSense 2.5.1 and Zabbix 5.2.6
I followed exactly what is described in the tutorial without any modification.

Thank you in advance for your help.

**Comment by carlo5henrique** [comment]
Excuse my lack of attention. I have changed the Item Type from Zabbix Active Agent to Zabbix Agent.

Everything is working beautifully.

@rbicelli, congratulations on your work in keeping this template up to date.

**Comment by rbicelli** [comment]
Thanks @carlo5henrique, I'm glad you liked my and contributors work. The misconfiguration of agent type is the top 1 issue. Will adjust the documentation soon.
