### ISSUE TITLE
false status gateway( 5)

### ISSUE THREAD

**Issue by ITMPGIT** [rbicelli/pfsense-zabbix-template#99]
my zabbix alerts whenever the gateways are with status=5 (down), even being UP, can you help?
pfsense: 2.5.2
zabbix: 5.0

**Comment by GuillaumeHullin** [comment]
Can you give a bit more details?

How do you see that your gateway is up in pfSense? Did you setup Gateway monitoring (System > Routing) with the option "Disable Gateway Monitoring Action" ?

**Comment by ITMPGIT** [comment]
> Can you give a bit more details?
> 
> How do you see that your gateway is up in pfSense? Did you setup Gateway monitoring (System > Routing) with the option "Disable Gateway Monitoring Action" ?

thanks for the reply , i have 2 links in failover and i use pfsense monitor.

I cleared the zabbix history and it worked!

**Comment by GuillaumeHullin** [comment]
Ok great to hear :) Don't forget to close the issue ;)
